#!/bin/bash

# Generated by Copilot 2025-04-23 17:30

echo "Starting CsetFlix application on network..."

# Get the local IP address
IP=$(hostname -I | cut -d' ' -f1)
if [ -z "$IP" ]; then
  IP="Could not determine local IP address"
fi

# Display access information
echo "====================================================="
echo "CsetFlix will be available at:"
echo "http://$IP:3000"
echo ""
echo "Share this URL with other devices on your network"
echo "====================================================="
echo ""

# Start the application with network access
npm run dev:network