// Generated by Copilot 2025-04-23
/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./components/**/*.{js,vue,ts}",
    "./layouts/**/*.vue",
    "./pages/**/*.vue",
    "./plugins/**/*.{js,ts}",
    "./app.vue",
    "./error.vue",
    "./assets/**/*.css"
  ],
  theme: {
    extend: {
      colors: {
        neutral: {
          900: '#171717',
          800: '#262626',
          700: '#404040',
        }
      }
    },
  },
  plugins: [require("daisyui")],
  daisyui: {
    themes: ["dark"]
  }
}
