<!-- Generated by Copilot 2025-04-23 15:30 -->
<template>
  <div class="container mx-auto p-4">
    <div v-if="loading" class="flex justify-center my-12">
      <span class="loading loading-spinner loading-lg text-red-600"></span>
    </div>
    
    <div v-else-if="error" class="alert alert-error shadow-lg mb-4">
      <div>
        <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current flex-shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" />
        </svg>
        <span>{{ error }}</span>
      </div>
    </div>
    
    <div v-else>
      <div class="mb-4">
        <button @click="router.back()" class="btn btn-ghost btn-sm">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18" />
          </svg>
          Back
        </button>
      </div>
      
      <div class="card bg-neutral-800 mb-8">
        <div class="card-body">
          <h2 class="card-title text-xl mb-2">Download "{{ movie?.title }}"</h2>
          
          <TorrentDownloader 
            v-if="movie" 
            :title="movie.title" 
          />
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import axios from 'axios'

// Define Movie interface inline to avoid import issues
interface Movie {
  id: number
  title: string
  poster_path: string
  overview: string
  release_date: string
  vote_average: number
}

const route = useRoute()
const router = useRouter()
const config = useRuntimeConfig()

const movieId = computed(() => route.params.id as string)
const movie = ref<Movie | null>(null)
const loading = ref(true)
const error = ref<string | null>(null)

onMounted(async () => {
  try {
    loading.value = true
    error.value = null
    
    const response = await axios.get(`${config.public.tmdbApiBaseUrl}/movie/${movieId.value}`, {
      params: {
        api_key: config.public.tmdbApiKey
      }
    })
    
    movie.value = response.data
  } catch (err: any) {
    error.value = err.message || 'Failed to load movie'
  } finally {
    loading.value = false
  }
})
</script>