// Generated by Copilot 2025-04-23 16:30

// Define the Movie interface
export interface Movie {
  id: number
  title: string
  poster_path: string
  overview: string
  release_date: string
  vote_average: number
}

// Create a namespace for compatibility with different import methods
namespace MovieTypes {
  export type MovieType = Movie;
}

// Export the namespace as default
export default MovieTypes;