// Generated by Copilot April 23, 2025 19:45
import { parse } from 'node-html-parser'

export default defineEventHandler(async (event) => {
  const query = getQuery(event)
  const searchQuery = query.q as string

  if (!searchQuery) {
    return { 
      success: false, 
      error: 'Search query is required', 
      results: [] 
    }
  }

  try {
    // Use 1337x as the torrent source - a popular public torrent site
    const searchUrl = `https://1337x.to/search/${encodeURIComponent(searchQuery)}/1/`
    
    const response = await fetch(searchUrl, {
      headers: {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
      }
    })

    if (!response.ok) {
      throw new Error(`Failed to fetch search results: ${response.statusText}`)
    }

    const html = await response.text()
    const root = parse(html)
    
    // Parse the torrent search results
    const torrents = root.querySelectorAll('table.table-list tbody tr').map(row => {
      const nameElement = row.querySelector('td.name a:nth-child(2)')
      const seedersElement = row.querySelector('td.seeds')
      const leechersElement = row.querySelector('td.leeches')
      const sizeElement = row.querySelector('td.size')
      const link = nameElement?.getAttribute('href')
      
      return {
        name: nameElement?.text.trim() || 'Unknown',
        seeders: seedersElement ? parseInt(seedersElement.text.trim(), 10) : 0,
        leechers: leechersElement ? parseInt(leechersElement.text.trim(), 10) : 0,
        size: sizeElement?.text.trim() || 'Unknown',
        link: link ? `https://1337x.to${link}` : null
      }
    })

    return {
      success: true,
      results: torrents
    }
  } catch (error: any) {
    console.error('Error searching for torrents:', error)
    
    // Return mock results to avoid complete failure
    return {
      success: false,
      error: error.message,
      results: [
        {
          name: `${searchQuery} 1080p BluRay x264`,
          size: '2.3 GB',
          seeders: 120,
          leechers: 10,
          magnetLink: `magnet:?xt=urn:btih:MOCK1&dn=${encodeURIComponent(searchQuery)}`
        },
        {
          name: `${searchQuery} 720p WEB-DL AAC5.1`,
          size: '1.4 GB',
          seeders: 85,
          leechers: 5,
          magnetLink: `magnet:?xt=urn:btih:MOCK2&dn=${encodeURIComponent(searchQuery)}`
        },
        {
          name: `${searchQuery} 2160p 4K HDR HEVC`,
          size: '8.7 GB',
          seeders: 42,
          leechers: 8,
          magnetLink: `magnet:?xt=urn:btih:MOCK3&dn=${encodeURIComponent(searchQuery)}`
        }
      ]
    }
  }
})