<!-- Generated by Copilot 2025-04-25 17:45 -->
<template>
  <div class="navbar bg-neutral-900 px-4 md:px-8 shadow-xl border-b border-neutral-800 sticky top-0 z-50 backdrop-blur-md bg-opacity-90">
    <div class="navbar-start">
      <div class="dropdown">
        <label tabindex="0" class="btn btn-ghost lg:hidden">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h8m-8 6h16" />
          </svg>
        </label>
        <ul tabindex="0" class="menu menu-sm dropdown-content mt-3 z-[1] p-2 shadow-lg bg-neutral-800 rounded-box w-52 border border-neutral-700">
          <li><NuxtLink to="/" class="hover:text-red-500 transition-colors">Home</NuxtLink></li>
          <li><NuxtLink to="/genres" class="hover:text-red-500 transition-colors">Genres</NuxtLink></li>
          <li><NuxtLink to="/search" class="hover:text-red-500 transition-colors">Search</NuxtLink></li>
        </ul>
      </div>
      <NuxtLink to="/" class="btn btn-ghost normal-case text-xl md:text-2xl text-red-600 font-bold hover:text-red-500 transition-colors">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 4v16M17 4v16M3 8h4m10 0h4M3 12h18M3 16h4m10 0h4M4 20h16a1 1 0 001-1V5a1 1 0 00-1-1H4a1 1 0 00-1 1v14a1 1 0 001 1z" />
        </svg>
        CsetFlix
      </NuxtLink>
    </div>
    
    <div class="navbar-center hidden lg:flex">
      <ul class="menu menu-horizontal px-1">
        <li>
          <NuxtLink to="/" class="text-base font-medium hover:text-red-500 transition-colors">Home</NuxtLink>
        </li>
        <li>
          <NuxtLink to="/genres" class="text-base font-medium hover:text-red-500 transition-colors">Genres</NuxtLink>
        </li>
        <li>
          <NuxtLink to="/search" class="text-base font-medium hover:text-red-500 transition-colors">Search</NuxtLink>
        </li>
      </ul>
    </div>
    
    <div class="navbar-end">
      <div class="form-control mr-2">
        <div class="relative">
          <input 
            type="text" 
            placeholder="Search movies..." 
            v-model="searchQuery" 
            @keyup.enter="searchMovies" 
            class="input input-bordered w-24 md:w-auto bg-neutral-800 pr-8 focus:ring-2 focus:ring-red-500 border-neutral-700"
          />
          <button 
            @click="searchMovies" 
            class="absolute top-1/2 right-2 -translate-y-1/2 text-gray-400 hover:text-red-500 transition-colors"
          >
            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
            </svg>
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { useMoviesStore } from '~/stores/movies'

const router = useRouter()
const route = useRoute()
const moviesStore = useMoviesStore()
const searchQuery = ref('')

async function searchMovies() {
  if (!searchQuery.value.trim()) return
  
  const query = encodeURIComponent(searchQuery.value.trim())
  
  // If we're already on the search page, directly perform the search
  if (route.path === '/search') {
    await moviesStore.searchMovies(searchQuery.value)
    searchQuery.value = ''
    // Update URL without navigation
    router.replace({ path: '/search', query: { q: query } })
  } else {
    // Navigate to search page with query
    router.push(`/search?q=${query}`)
    searchQuery.value = ''
  }
}
</script>

<style scoped>
.router-link-active {
  color: theme('colors.red.500');
  font-weight: 600;
}

.navbar {
  transition: background-opacity 0.3s ease;
}
</style>