<!-- Generated by Copilot 2025-04-23 14:10 -->
<template>
  <div class="navbar bg-neutral-800 px-4 md:px-8 shadow-lg">
    <div class="navbar-start">
      <div class="dropdown">
        <label tabindex="0" class="btn btn-ghost lg:hidden">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h8m-8 6h16" />
          </svg>
        </label>
        <ul tabindex="0" class="menu menu-sm dropdown-content mt-3 z-[1] p-2 shadow bg-neutral-800 rounded-box w-52">
          <li><NuxtLink to="/">Home</NuxtLink></li>
          <li><NuxtLink to="/movies">Movies</NuxtLink></li>
          <li><NuxtLink to="/search">Search</NuxtLink></li>
        </ul>
      </div>
      <NuxtLink to="/" class="btn btn-ghost normal-case text-xl text-red-600">CsetFlix</NuxtLink>
    </div>
    
    <div class="navbar-center hidden lg:flex">
      <ul class="menu menu-horizontal px-1">
        <li><NuxtLink to="/" class="navbar-item">Home</NuxtLink></li>
        <li><NuxtLink to="/movies" class="navbar-item">Movies</NuxtLink></li>
        <li><NuxtLink to="/search" class="navbar-item">Search</NuxtLink></li>
      </ul>
    </div>
    
    <div class="navbar-end">
      <div class="form-control mr-2">
        <input type="text" placeholder="Search movies..." v-model="searchQuery" @keyup.enter="searchMovies" 
               class="input input-bordered w-24 md:w-auto bg-neutral-700" />
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
const router = useRouter()
const searchQuery = ref('')

function searchMovies() {
  if (searchQuery.value) {
    router.push(`/search?q=${encodeURIComponent(searchQuery.value)}`)
    searchQuery.value = ''
  }
}
</script>