<!-- Generated by Copilot 2025-04-23 14:15 -->
<template>
  <div class="card-movie h-full">
    <figure class="relative h-60">
      <img 
        :src="posterUrl" 
        :alt="movie.title" 
        class="w-full h-full object-cover"
        @error="useDefaultPoster" 
      />
      <div class="absolute top-2 right-2 badge badge-accent">{{ formatRating }}</div>
    </figure>
    <div class="card-body">
      <h2 class="card-title text-lg">{{ movie.title }}</h2>
      <p class="text-sm opacity-70">{{ formatDate }}</p>
      <p class="text-sm line-clamp-3">{{ movie.overview || 'No description available.' }}</p>
      <div class="card-actions justify-between mt-4">
        <button @click="showDetails" class="btn btn-sm btn-outline">Details</button>
        <button @click="downloadMovie" class="btn btn-sm btn-primary">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
          </svg>
          Download
        </button>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
// Generated by Copilot 2025-04-23 16:35
interface Movie {
  id: number;
  title: string;
  poster_path: string;
  overview: string;
  release_date: string;
  vote_average: number;
}

import { useTorrentStore } from '~/stores/torrent'

const props = defineProps<{
  movie: Movie
}>()

const config = useRuntimeConfig()
const router = useRouter()
const torrentStore = useTorrentStore()

const posterUrl = computed(() => {
  if (!props.movie.poster_path) return '/no-poster.jpg'
  return `${config.public.tmdbImageBaseUrl}/w500${props.movie.poster_path}`
})

const formatRating = computed(() => {
  return props.movie.vote_average?.toFixed(1) || 'N/A'
})

const formatDate = computed(() => {
  if (!props.movie.release_date) return 'Unknown date'
  return new Date(props.movie.release_date).toLocaleDateString()
})

function useDefaultPoster(event: Event) {
  const target = event.target as HTMLImageElement
  target.src = '/no-poster.jpg'
}

function showDetails() {
  router.push(`/movie/${props.movie.id}`)
}

function downloadMovie() {
  torrentStore.searchTorrents(props.movie.title)
  router.push(`/download/${props.movie.id}`)
}
</script>