<!-- Generated by Copilot 2025-04-25 17:40 -->
<template>
  <div class="card bg-neutral-800 h-full hover:scale-[1.02] transition-transform duration-300 shadow-xl">
    <figure class="relative h-60 overflow-hidden bg-neutral-700 cursor-pointer" @click="showDetails">
      <!-- Favorite toggle button -->
      <button
        @click.stop="toggleFavorite"
        class="absolute top-2 left-2 z-10 rounded-full p-1 bg-neutral-900/70 hover:bg-neutral-900/90 text-red-500"
      >
        <svg v-if="isFavorite" xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 fill-current" viewBox="0 0 24 24">
          <path fill-rule="evenodd" d="M3.172 5.172a4 4 0 015.656 0L12 8.343l3.172-3.171a4 4 0 115.656 5.656L12 21.657l-8.828-8.829a4 4 0 010-5.656z" clip-rule="evenodd" />
        </svg>
        <svg v-else xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3.172 5.172a4 4 0 015.656 0L12 8.343l3.172-3.171a4 4 0 115.656 5.656L12 21.657l-8.828-8.829a4 4 0 010-5.656z" />
        </svg>
      </button>
      <template v-if="imageLoaded === false">
        <div class="w-full h-full flex items-center justify-center bg-neutral-700 p-4">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-16 w-16 text-neutral-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1" d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />
          </svg>
          <div class="absolute bottom-0 left-0 w-full h-1/2 bg-gradient-to-t from-neutral-900 to-transparent"></div>
        </div>
      </template>
      <img 
        v-show="imageLoaded !== false"
        :src="posterUrl" 
        :alt="movie.title" 
        class="w-full h-full object-cover transition-transform duration-500 hover:scale-105"
        @error="handleImageError" 
        @load="imageLoaded = true"
      />
      <div class="absolute bottom-0 left-0 w-full h-1/2 bg-gradient-to-t from-neutral-900 to-transparent"></div>
      <div class="absolute top-2 right-2">
        <div class="badge badge-accent shadow-lg">{{ formatRating }}</div>
      </div>
      <div class="absolute bottom-2 left-2">
        <span class="text-xs bg-neutral-800/80 px-2 py-1 rounded-md">{{ formatDate }}</span>
      </div>
    </figure>
    <div class="card-body p-4">
      <h2 class="card-title text-lg line-clamp-2 mb-2">{{ movie.title }}</h2>
      <p class="text-sm line-clamp-2 text-gray-300 mb-4">{{ movie.overview || 'No description available.' }}</p>
      <div class="card-actions justify-between mt-auto">
        <button @click="showDetails" class="btn btn-sm btn-outline btn-ghost">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
          </svg>
          Details
        </button>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
// Generated by Copilot 2025-04-25 17:40
import type { Movie } from '~/types/movie'
import { useFavoritesStore } from '~/stores/favorites'

const props = defineProps<{
  movie: Movie
}>()

const config = useRuntimeConfig()
const router = useRouter()
const favoritesStore = useFavoritesStore()
const imageLoaded = ref<boolean | null>(null)
const isFavorite = computed(() => favoritesStore.isFavorite(props.movie.id))

function toggleFavorite() {
  favoritesStore.toggleFavorite(props.movie)
}

const posterUrl = computed(() => {
  if (!props.movie.poster_path) return '/no-poster.jpg'
  return `${config.public.tmdbImageBaseUrl}/w500${props.movie.poster_path}`
})

const formatRating = computed(() => {
  return props.movie.vote_average?.toFixed(1) || 'N/A'
})

const formatDate = computed(() => {
  if (!props.movie.release_date) return 'Unknown date'
  const date = new Date(props.movie.release_date)
  return date.getFullYear().toString()
})

function handleImageError() {
  imageLoaded.value = false
}

function showDetails() {
  router.push(`/movie/${props.movie.id}`)
}

</script>