<!-- Generated by Copilot January 26, 2025 -->
<template>
  <div v-if="isVisible" class="fixed inset-0 bg-black bg-opacity-90 flex items-center justify-center z-50">
    <div class="w-full h-full max-w-6xl max-h-screen p-4">
      <div class="bg-black rounded-lg overflow-hidden h-full flex flex-col">
        <!-- Header -->
        <div class="flex justify-between items-center p-4 bg-gray-800">
          <h3 class="text-white text-lg font-semibold">
            {{ movieTitle || 'Torrent Player' }}
          </h3>
          <button 
            @click="closePlayer"
            class="text-white hover:text-red-400 text-2xl"
          >
            ×
          </button>
        </div>
        
        <!-- Loading State -->
        <div v-if="isLoading" class="flex-1 flex items-center justify-center">
          <div class="text-center text-white">
            <div class="loading loading-spinner loading-lg text-red-600 mb-4"></div>
            <p class="text-lg mb-2">{{ loadingText }}</p>
            <p class="text-sm text-gray-400 mt-2">
              Setting up stream...
            </p>
          </div>
        </div>
        
        <!-- Error State -->
        <div v-else-if="error" class="flex-1 flex items-center justify-center">
          <div class="text-center text-white max-w-md">
            <div class="text-red-500 text-6xl mb-4">⚠️</div>
            <h3 class="text-lg font-semibold text-red-400 mb-2">Stream Error</h3>
            <p class="text-gray-300 mb-4">{{ error }}</p>
            <div class="space-x-2">
              <button 
                @click="retryStream"
                class="bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded"
              >
                Retry
              </button>
              <button 
                @click="openInNewTab"
                class="bg-green-600 hover:bg-green-700 text-white px-4 py-2 rounded"
              >
                Open in Webtor.io
              </button>
              <button 
                @click="closePlayer"
                class="bg-red-600 hover:bg-red-700 text-white px-4 py-2 rounded"
              >
                Close
              </button>
            </div>
          </div>
        </div>
        
        <!-- Embedded Player -->
        <div v-else-if="embedUrl" class="flex-1">
          <iframe
            :src="embedUrl"
            class="w-full h-full border-0"
            allowfullscreen
            allow="autoplay; encrypted-media"
            sandbox="allow-same-origin allow-scripts allow-popups allow-forms"
          />
        </div>
        
        <!-- Stream Info -->
        <div v-if="embedUrl && !isLoading" class="p-4 bg-gray-800 text-white text-sm">
          <div class="grid grid-cols-2 md:grid-cols-3 gap-4">
            <div>
              <span class="text-gray-400">Status:</span> {{ streamStatus }}
            </div>
            <div>
              <span class="text-gray-400">Source:</span> Webtor.io
            </div>
            <div>
              <span class="text-gray-400">Format:</span> Web Stream
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
// Generated by Copilot January 26, 2025

interface Props {
  magnetUri: string
  isVisible: boolean
}

const props = defineProps<Props>()
const emit = defineEmits<{
  close: []
}>()

const embedUrl = ref<string>('')
const isLoading = ref(true)
const error = ref<string>('')
const loadingText = ref('Initializing stream...')
const movieTitle = ref('')
const streamStatus = ref('Connecting')

watch(() => props.isVisible, async (visible) => {
  console.log('🎬 Torrent Player visibility changed:', visible)
  
  if (visible && props.magnetUri) {
    console.log('🔗 Starting stream for magnet:', props.magnetUri.substring(0, 50) + '...')
    await initializeStream()
  } else if (!visible) {
    console.log('🚫 Player closed, cleaning up...')
    cleanup()
  }
}, { immediate: true })

async function initializeStream() {
  console.log('🚀 Initializing stream...')
  
  isLoading.value = true
  error.value = ''
  loadingText.value = 'Setting up torrent stream...'
  streamStatus.value = 'Connecting'
  
  try {
    // Extract movie title from magnet URI
    const dnMatch = props.magnetUri.match(/dn=([^&]+)/)
    if (dnMatch) {
      movieTitle.value = decodeURIComponent(dnMatch[1].replace(/\+/g, ' '))
      console.log('🎭 Movie title:', movieTitle.value)
    }
    
    loadingText.value = 'Creating embed link...'
    
    // Create embed URL for webtor.io
    const encodedMagnet = encodeURIComponent(props.magnetUri)
    const encodedTitle = encodeURIComponent(movieTitle.value || 'Movie')
    
    // Build URL without empty parameters to avoid "wrong args provided" error
    embedUrl.value = `https://webtor.io/web?magnet=${encodedMagnet}&lang=en&title=${encodedTitle}`
    
    console.log('🌊 Embed URL created:', embedUrl.value)
    
    // Simulate loading time (reduced for testing)
    await new Promise(resolve => setTimeout(resolve, 1000))
    
    isLoading.value = false
    streamStatus.value = 'Ready'
    
  } catch (err) {
    console.error('❌ Failed to initialize stream:', err)
    error.value = 'Failed to initialize stream. This might be due to network issues or the torrent not being available.'
    isLoading.value = false
    streamStatus.value = 'Error'
  }
}

function retryStream() {
  console.log('🔄 Retrying stream...')
  initializeStream()
}

function openInNewTab() {
  if (embedUrl.value) {
    window.open(embedUrl.value, '_blank')
  }
}

function closePlayer() {
  console.log('🚪 Closing player')
  emit('close')
}

function cleanup() {
  console.log('🧹 Cleaning up stream...')
  
  embedUrl.value = ''
  isLoading.value = true
  error.value = ''
  movieTitle.value = ''
  streamStatus.value = 'Disconnected'
  
  console.log('✅ Cleanup completed')
}

onUnmounted(() => {
  console.log('🏁 TorrentPlayer unmounting')
  cleanup()
})
</script>
