<!-- Generated by Copilot January 26, 2025 -->
<template>
  <div v-if="isVisible" class="fixed inset-0 bg-black bg-opacity-90 flex items-center justify-center z-50">
    <div class="w-full h-full max-w-6xl max-h-screen p-4">
      <div class="bg-black rounded-lg overflow-hidden h-full flex flex-col">
        <!-- Header -->
        <div class="flex justify-between items-center p-4 bg-gray-800">
          <h3 class="text-white text-lg font-semibold">
            {{ movieTitle || 'Torrent Player' }}
          </h3>
          <button 
            @click="closePlayer"
            class="text-white hover:text-red-400 text-2xl"
          >
            ×
          </button>
        </div>
        
        <!-- Loading State -->
        <div v-if="isLoading" class="flex-1 flex items-center justify-center">
          <div class="text-center text-white">
            <div class="loading loading-spinner loading-lg text-red-600 mb-4"></div>
            <p class="text-lg mb-2">{{ loadingText }}</p>
            <p class="text-sm text-gray-400 mt-2">{{ statusText }}</p>
            <div v-if="downloadProgress > 0" class="mt-4">
              <div class="w-64 bg-gray-700 rounded-full h-2 mx-auto">
                <div 
                  class="bg-blue-600 h-2 rounded-full transition-all duration-300" 
                  :style="{ width: downloadProgress + '%' }"
                ></div>
              </div>
              <p class="text-xs text-gray-400 mt-2">{{ downloadProgress.toFixed(1) }}% downloaded</p>
            </div>
          </div>
        </div>
        
        <!-- Error State -->
        <div v-else-if="error" class="flex-1 flex items-center justify-center">
          <div class="text-center text-white max-w-md">
            <div class="text-red-500 text-6xl mb-4">⚠️</div>
            <h3 class="text-lg font-semibold text-red-400 mb-2">Stream Error</h3>
            <p class="text-gray-300 mb-4">{{ error }}</p>
            <div class="space-x-2">
              <button 
                @click="retryStream"
                class="bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded"
              >
                Retry
              </button>
              <button 
                @click="closePlayer"
                class="bg-red-600 hover:bg-red-700 text-white px-4 py-2 rounded"
              >
                Close
              </button>
            </div>
          </div>
        </div>
        
        <!-- Video Player -->
        <div v-else-if="videoUrl" class="flex-1">
          <video
            ref="videoElement"
            :src="videoUrl"
            class="w-full h-full"
            controls
            autoplay
            @loadstart="onVideoLoadStart"
            @loadeddata="onVideoLoaded"
            @error="onVideoError"
          />
        </div>
        
        <!-- Stream Info -->
        <div v-if="!isLoading && !error" class="p-4 bg-gray-800 text-white text-sm">
          <div class="grid grid-cols-2 md:grid-cols-4 gap-4">
            <div>
              <span class="text-gray-400">Status:</span> {{ streamStatus }}
            </div>
            <div>
              <span class="text-gray-400">Peers:</span> {{ peerCount }}
            </div>
            <div>
              <span class="text-gray-400">Download:</span> {{ downloadSpeed }}
            </div>
            <div>
              <span class="text-gray-400">Upload:</span> {{ uploadSpeed }}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
// Generated by Copilot January 26, 2025

// Add global WebTorrent type declaration
declare global {
  interface Window {
    WebTorrent: any
  }
}

interface Props {
  magnetUri: string
  isVisible: boolean
}

const props = defineProps<Props>()
const emit = defineEmits<{
  close: []
}>()

const videoElement = ref<HTMLVideoElement>()
const movieTitle = ref('')
const isLoading = ref(true)
const error = ref('')
const loadingText = ref('Initializing...')
const statusText = ref('')
const videoUrl = ref('')
const streamStatus = ref('Connecting')
const downloadProgress = ref(0)
const peerCount = ref(0)
const downloadSpeed = ref('0 B/s')
const uploadSpeed = ref('0 B/s')

let client: any = null
let torrent: any = null

onMounted(() => {
  if (props.isVisible && props.magnetUri) {
    nextTick(() => {
      initializeStream()
    })
  }
})

watch(() => props.isVisible, async (visible) => {
  if (visible && props.magnetUri) {
    await initializeStream()
  } else if (!visible) {
    cleanup()
  }
})

async function initializeStream() {
  isLoading.value = true
  error.value = ''
  loadingText.value = 'Setting up WebTorrent...'
  statusText.value = 'Initializing torrent client'
  streamStatus.value = 'Connecting'
  
  try {
    // Extract movie title
    extractMovieTitle()
    
    // Cleanup previous session
    cleanup()
    
    // Load WebTorrent from CDN for better compatibility
    if (process.client) {
      if (!window.WebTorrent) {
        loadingText.value = 'Loading WebTorrent...'
        statusText.value = 'Loading torrent library'
        
        // Load WebTorrent from CDN
        await loadWebTorrentFromCDN()
      }
      
      // Create WebTorrent client
      statusText.value = 'Creating torrent client...'
      client = new window.WebTorrent()
      
      loadingText.value = 'Adding torrent...'
      statusText.value = 'Adding magnet link to client'
      
      // Add torrent
      torrent = client.add(props.magnetUri, {
        announce: [
          'wss://tracker.btorrent.xyz',
          'wss://tracker.openwebtorrent.com',
          'wss://tracker.webtorrent.io'
        ]
      })
      
      setupTorrentEvents()
    } else {
      error.value = 'WebTorrent requires a browser environment'
      isLoading.value = false
    }
    
  } catch (err) {
    console.error('Failed to initialize stream:', err)
    error.value = 'Failed to initialize torrent stream. Please try again.'
    isLoading.value = false
  }
}

function loadWebTorrentFromCDN(): Promise<void> {
  return new Promise((resolve, reject) => {
    if (window.WebTorrent) {
      resolve()
      return
    }
    
    const script = document.createElement('script')
    script.src = 'https://cdn.jsdelivr.net/npm/webtorrent@latest/webtorrent.min.js'
    script.onload = () => resolve()
    script.onerror = () => reject(new Error('Failed to load WebTorrent from CDN'))
    document.head.appendChild(script)
  })
}

function setupTorrentEvents() {
  if (!torrent) return
  
  torrent.on('metadata', () => {
    console.log('Torrent metadata received')
    loadingText.value = 'Finding video file...'
    statusText.value = `Found ${torrent!.files.length} files`
    
    // Find the largest video file
    const videoFile = torrent!.files.find((file: any) => 
      /\.(mp4|avi|mkv|mov|wmv|flv|webm|m4v)$/i.test(file.name)
    ) || torrent!.files.reduce((largest: any, file: any) => 
      file.length > largest.length ? file : largest
    )
    
    if (videoFile) {
      movieTitle.value = videoFile.name
      loadingText.value = 'Preparing video stream...'
      statusText.value = `Streaming: ${videoFile.name}`
      
      // Create blob URL for video streaming
      videoFile.getBlobURL((err: Error | null, url?: string) => {
        if (err) {
          console.error('Error getting blob URL:', err)
          error.value = 'Failed to create video stream'
          isLoading.value = false
          return
        }
        
        if (url) {
          videoUrl.value = url
          isLoading.value = false
          streamStatus.value = 'Streaming'
        }
      })
    } else {
      error.value = 'No video file found in torrent'
      isLoading.value = false
    }
  })
  
  torrent.on('download', () => {
    if (torrent) {
      downloadProgress.value = (torrent.progress * 100)
      downloadSpeed.value = formatBytes(torrent.downloadSpeed) + '/s'
      uploadSpeed.value = formatBytes(torrent.uploadSpeed) + '/s'
    }
  })
  
  torrent.on('wire', () => {
    if (torrent) {
      peerCount.value = torrent.numPeers
    }
  })
  
  torrent.on('error', (err: Error) => {
    console.error('Torrent error:', err)
    error.value = 'Torrent error: ' + err.message
    isLoading.value = false
  })
  
  torrent.on('ready', () => {
    console.log('Torrent ready')
    streamStatus.value = 'Ready'
  })
}

function extractMovieTitle() {
  try {
    const dnMatch = props.magnetUri.match(/dn=([^&]+)/)
    if (dnMatch) {
      movieTitle.value = decodeURIComponent(dnMatch[1].replace(/\+/g, ' '))
    }
  } catch (error) {
    movieTitle.value = 'Unknown Movie'
  }
}

function formatBytes(bytes: number): string {
  if (bytes === 0) return '0 B'
  const k = 1024
  const sizes = ['B', 'KB', 'MB', 'GB']
  const i = Math.floor(Math.log(bytes) / Math.log(k))
  return parseFloat((bytes / Math.pow(k, i)).toFixed(1)) + ' ' + sizes[i]
}

function retryStream() {
  initializeStream()
}

function onVideoLoadStart() {
  console.log('Video load started')
}

function onVideoLoaded() {
  console.log('Video loaded successfully')
  streamStatus.value = 'Playing'
}

function onVideoError(event: Event) {
  console.error('Video error:', event)
  error.value = 'Video playback error. The file might be corrupted or in an unsupported format.'
}

function closePlayer() {
  cleanup()
  emit('close')
}

function cleanup() {
  if (torrent) {
    torrent.destroy()
    torrent = null
  }
  
  if (client) {
    client.destroy()
    client = null
  }
  
  if (videoUrl.value) {
    URL.revokeObjectURL(videoUrl.value)
    videoUrl.value = ''
  }
  
  isLoading.value = true
  error.value = ''
  downloadProgress.value = 0
  peerCount.value = 0
  downloadSpeed.value = '0 B/s'
  uploadSpeed.value = '0 B/s'
  streamStatus.value = 'Disconnected'
}

onUnmounted(() => {
  cleanup()
})
</script>
