<!-- Generated by Copilot July 26, 2025 -->
<template>
  <div>
    <!-- Torrent Player Modal -->
    <TorrentPlayer 
      v-if="selectedMagnetUri"
      :magnet-uri="selectedMagnetUri"
      :is-visible="showPlayer"
      @close="closePlayer"
    />

    <!-- Webtor Modal -->
    <div v-if="showWebtorModal" class="fixed inset-0 bg-black bg-opacity-75 flex items-center justify-center z-50">
      <div class="bg-gray-900 rounded-lg p-6 w-[95vw] h-[95vh] max-w-7xl overflow-hidden flex flex-col">
        <!-- Header -->
        <div class="flex justify-between items-center mb-4">
          <h3 class="text-xl font-semibold text-white">Webtor.io Stream</h3>
          <button @click="closeWebtorModal" class="text-white hover:text-red-400 text-2xl">×</button>
        </div>
        
        <!-- Auto-stream Info Section -->
        <div class="mb-4 p-4 bg-gray-800 rounded-lg flex-shrink-0">
          <div class="flex items-center gap-2 mb-2">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-green-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
            <span class="text-green-400 font-medium">Webtor.io Stream Ready</span>
          </div>
          <p class="text-sm text-gray-300">
            The magnet link has been automatically loaded into Webtor.io. The stream should start automatically below.
          </p>
          <div class="mt-2 p-2 bg-gray-700 rounded text-xs text-gray-400 font-mono truncate">
            {{ selectedMagnetUri }}
          </div>
        </div>
        
        <!-- Webtor iframe -->
        <div class="flex-1 min-h-0">
          <iframe
            :src="webtorUrl"
            class="w-full h-full border-0 rounded"
            allowfullscreen
            allow="autoplay; encrypted-media"
          />
        </div>
      </div>
    </div>

    <div v-if="torrentStore.loading && torrentStore.titleSearchLoading" class="flex justify-center my-8">
      <div class="flex flex-col items-center">
        <span class="loading loading-spinner loading-lg text-red-600 mb-2"></span>
        <p>Searching multiple torrent sources...</p>
      </div>
    </div>
    
    <div v-else-if="torrentStore.magnetLoading" class="flex justify-center my-8">
      <div class="flex flex-col items-center">
        <span class="loading loading-spinner loading-md text-red-600 mb-2"></span>
        <p>Fetching magnet link for {{ torrentStore.selectedTorrent?.name }}...</p>
      </div>
    </div>
    
    <div v-else-if="torrentStore.connectionError" class="alert alert-warning shadow-lg mb-4">
      <div>
        <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current flex-shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
        </svg>
        <div>
          <span class="font-bold">Connection issue</span>
          <p class="text-sm mt-1">{{ torrentStore.error }}</p>
          <div class="mt-3" v-if="torrentStore.downloadSuccess">
            <p class="text-success">Download started successfully.</p>
          </div>
        </div>
      </div>
    </div>
    
    <div v-else-if="torrentStore.downloadSuccess" class="alert alert-success shadow-lg mb-4">
      <div>
        <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current flex-shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
        </svg>
        <span>Download started successfully!</span>
      </div>
    </div>
    
    <div v-else>
      <!-- Title-based Results Section - Now First -->
      <div class="mb-8">
        <div class="flex items-center mb-4">
          <h3 class="text-lg font-semibold">BitSearch Results</h3>
          <div class="badge badge-neutral ml-3">Title based</div>
          <div v-if="torrentStore.titleSearchLoading" class="ml-auto">
            <span class="loading loading-spinner loading-sm text-red-600"></span>
          </div>
        </div>
        
        <div v-if="torrentStore.titleSearchError" class="alert alert-warning mb-6">
          <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
          </svg>
          <span>{{ torrentStore.titleSearchError }}</span>
        </div>
        
        <div v-if="torrentStore.titleSearchResults.length > 0" class="overflow-x-auto mb-6">
          <table class="table w-full">
            <thead>
              <tr>
                <th>Name</th>
                <th>Size</th>
                <th>Seeders</th>
                <th>Source</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
              <tr v-for="torrent in torrentStore.titleSearchResults" :key="torrent.name" class="hover">
                <td class="max-w-md truncate">{{ torrent.name }}</td>
                <td>{{ torrent.size }}</td>
                <td>
                  <span :class="{'text-success': torrent.seeders > 20, 'text-warning': torrent.seeders > 5 && torrent.seeders <= 20, 'text-error': torrent.seeders <= 5}">
                    {{ torrent.seeders }}
                  </span>
                </td>
                <td>
                  <span class="badge badge-sm">{{ torrent.source }}</span>
                </td>
                <td>
                  <div class="flex gap-2">
                    <button @click="openWebtor(torrent)" 
                            class="btn btn-sm bg-purple-600 hover:bg-purple-700 border-purple-700 text-white">
                      <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 12a9 9 0 01-9 9m9-9a9 9 0 00-9-9m9 9H3m9 0l3-3m-3 3l3 3" />
                      </svg>
                      Webtor
                    </button>
                    <button @click="streamTorrent(torrent)" 
                            class="btn btn-sm bg-green-600 hover:bg-green-700 border-green-700 text-white">
                      <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M14.828 14.828a4 4 0 01-5.656 0M9 10h1m4 0h1m-6 4h1m4 0h1m2-7a9 9 0 11-18 0 9 9 0 0118 0z" />
                      </svg>
                      Stream
                    </button>
                    <button @click="downloadTorrent(torrent)" 
                            class="btn btn-sm bg-red-600 hover:bg-red-700 border-red-700 text-white">
                      <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                      </svg>
                      Download
                    </button>
                  </div>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
        
        <div v-else-if="!torrentStore.titleSearchLoading" class="text-center mb-6 py-6 bg-neutral-800/50 rounded-lg">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-12 w-12 mx-auto text-neutral-500 mb-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M9.75 17L9 20l-1 1h8l-1-1-.75-3M3 13h18M5 17h14a2 2 0 002-2V5a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
          </svg>
          <p class="text-neutral-400">No alternative torrents found for this title.</p>
        </div>
      </div>
      
      <!-- IMDB-based Results Section - Now Second -->
      <div class="mt-10 mb-8">
        <div class="flex items-center mb-4">
          <h3 class="text-lg font-semibold">TorrentIO Results</h3>
          <div class="badge badge-neutral ml-3">IMDB ID based</div>
          <div v-if="torrentStore.loading" class="ml-auto">
            <span class="loading loading-spinner loading-sm text-red-600"></span>
          </div>
        </div>
        
        <div v-if="torrentStore.error" class="alert alert-warning mb-6">
          <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
          </svg>
          <span>{{ torrentStore.error }}</span>
        </div>
        
        <div v-if="torrentStore.searchResults.length > 0" class="overflow-x-auto mb-6">
          <table class="table w-full">
            <thead>
              <tr>
                <th>Name</th>
                <th>Size</th>
                <th>Seeders</th>
                <th>Leechers</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
              <tr v-for="torrent in torrentStore.searchResults" :key="torrent.name" class="hover">
                <td class="max-w-md truncate">{{ torrent.name }}</td>
                <td>{{ torrent.size }}</td>
                <td>
                  <span :class="{'text-success': torrent.seeders > 20, 'text-warning': torrent.seeders > 5 && torrent.seeders <= 20, 'text-error': torrent.seeders <= 5}">
                    {{ torrent.seeders }}
                  </span>
                </td>
                <td>{{ torrent.leechers }}</td>
                <td>
                  <div class="flex gap-2">
                    <button @click="openWebtor(torrent)" 
                            class="btn btn-sm bg-purple-600 hover:bg-purple-700 border-purple-700 text-white">
                      <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 12a9 9 0 01-9 9m9-9a9 9 0 00-9-9m9 9H3m9 0l3-3m-3 3l3 3" />
                      </svg>
                      Webtor
                    </button>
                    <button @click="streamTorrent(torrent)" 
                            class="btn btn-sm bg-green-600 hover:bg-green-700 border-green-700 text-white">
                      <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M14.828 14.828a4 4 0 01-5.656 0M9 10h1m4 0h1m-6 4h1m4 0h1m2-7a9 9 0 11-18 0 9 9 0 0118 0z" />
                      </svg>
                      Stream
                    </button>
                    <button @click="downloadTorrent(torrent)" 
                            class="btn btn-sm bg-red-600 hover:bg-red-700 border-red-700 text-white">
                      <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                      </svg>
                      Download
                    </button>
                  </div>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
        
        <div v-else-if="!torrentStore.loading" class="text-center mb-6 py-6 bg-neutral-800/50 rounded-lg">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-12 w-12 mx-auto text-neutral-500 mb-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M9.75 17L9 20l-1 1h8l-1-1-.75-3M3 13h18M5 17h14a2 2 0 002-2V5a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
          </svg>
          <p class="text-neutral-400">No torrents found on TorrentIO.</p>
        </div>
      </div>
      
      <div v-if="!torrentStore.loading && !torrentStore.titleSearchLoading && !torrentStore.searchResults.length && !torrentStore.titleSearchResults.length" 
           class="alert alert-error shadow-lg my-8">
        <div>
          <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current flex-shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" />
          </svg>
          <span>No torrents found from any source. Try searching with a different title.</span>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
// Generated by Copilot July 26, 2025
import { useTorrentStore } from '~/stores/torrent'

const props = defineProps<{
  title: string
}>()

const torrentStore = useTorrentStore()

// Torrent streaming state
const showPlayer = ref(false)
const selectedMagnetUri = ref('')

// Webtor modal state
const showWebtorModal = ref(false)
const magnetCopied = ref(false)
const magnetInput = ref<HTMLInputElement>()
const webtorUrl = ref('')

onMounted(() => {
  initSearch()
})

onUnmounted(() => {
  // Reset state when component is removed from DOM
  torrentStore.resetSearchState()
})

// Watch for title changes to handle navigation between different movies
watch(() => props.title, (newTitle, oldTitle) => {
  if (newTitle !== oldTitle) {
    console.log('Movie changed, searching new torrents for:', newTitle)
    initSearch()
  }
}, { immediate: true })

function initSearch() {
  if (props.title) {
    torrentStore.searchTorrents(props.title)
  }
}

function downloadTorrent(torrent: any) {
  torrentStore.downloadTorrent(torrent)
}

async function streamTorrent(torrent: any) {
  try {
    // Get magnet URI from the torrent
    let magnetUri = ''
    
    if (torrent.magnet) {
      magnetUri = torrent.magnet
    } else if (torrent.magnetLink) {
      magnetUri = torrent.magnetLink
    } else if (torrent.infoHash) {
      magnetUri = `magnet:?xt=urn:btih:${torrent.infoHash}&dn=${encodeURIComponent(torrent.name)}`
    } else {
      // Try to get magnet link via the store
      await torrentStore.getMagnetLink(torrent)
      magnetUri = torrentStore.currentMagnet
    }
    
    if (!magnetUri) {
      throw new Error('Could not obtain magnet URI for this torrent')
    }
    
    selectedMagnetUri.value = magnetUri
    showPlayer.value = true
  } catch (error) {
    console.error('Error starting stream:', error)
    // You might want to show a toast notification here
    alert('Failed to start streaming: ' + (error as Error).message)
  }
}

function closePlayer() {
  showPlayer.value = false
  selectedMagnetUri.value = ''
}

async function openWebtor(torrent: any) {
  try {
    // Get magnet URI from the torrent
    let magnetUri = ''
    
    if (torrent.magnet) {
      magnetUri = torrent.magnet
    } else if (torrent.magnetLink) {
      magnetUri = torrent.magnetLink
    } else if (torrent.infoHash) {
      magnetUri = `magnet:?xt=urn:btih:${torrent.infoHash}&dn=${encodeURIComponent(torrent.name)}`
    } else {
      // Try to get magnet link via the store
      await torrentStore.getMagnetLink(torrent)
      magnetUri = torrentStore.currentMagnet
    }
    
    if (!magnetUri) {
      throw new Error('Could not obtain magnet URI for this torrent')
    }
    
    // Extract movie title from magnet URI or torrent name
    let movieTitle = torrent.name || 'Movie'
    const dnMatch = magnetUri.match(/dn=([^&]+)/)
    if (dnMatch) {
      movieTitle = decodeURIComponent(dnMatch[1].replace(/\+/g, ' '))
    }
    
    // Construct webtor.io URL with magnet parameter (similar to TorrentPlayerNew.vue)
    const encodedMagnet = encodeURIComponent(magnetUri)
    webtorUrl.value = `https://webtor.io/web?magnet=${encodedMagnet}&lang=en&poster=&title=${encodeURIComponent(movieTitle)}`
    
    selectedMagnetUri.value = magnetUri
    showWebtorModal.value = true
    magnetCopied.value = false
  } catch (error) {
    console.error('Error opening Webtor:', error)
    alert('Failed to get magnet link: ' + (error as Error).message)
  }
}

function closeWebtorModal() {
  showWebtorModal.value = false
  selectedMagnetUri.value = ''
  magnetCopied.value = false
  webtorUrl.value = ''
}

function selectMagnetText() {
  if (magnetInput.value) {
    magnetInput.value.select()
    magnetInput.value.setSelectionRange(0, 99999) // For mobile devices
  }
}

async function copyMagnetToClipboard() {
  try {
    await navigator.clipboard.writeText(selectedMagnetUri.value)
    magnetCopied.value = true
    
    // Reset copied status after 3 seconds
    setTimeout(() => {
      magnetCopied.value = false
    }, 3000)
  } catch (error) {
    console.error('Failed to copy magnet link:', error)
    // Fallback: select text for manual copy
    selectMagnetText()
    
    // Try document.execCommand as fallback
    try {
      document.execCommand('copy')
      magnetCopied.value = true
      setTimeout(() => {
        magnetCopied.value = false
      }, 3000)
    } catch (fallbackError) {
      alert('Please manually copy the magnet link')
    }
  }
}
</script>