<!-- Generated by Copilot July 26, 2025 -->
<template>
  <div>
    <!-- Torrent Player Modal -->
    <TorrentPlayer 
      v-if="selectedMagnetUri"
      :magnet-uri="selectedMagnetUri"
      :is-visible="showPlayer"
      @close="closePlayer"
    />

    <!-- Webtor Modal with SDK -->
    <div v-if="showWebtorModal" class="fixed inset-0 bg-black bg-opacity-75 flex items-center justify-center z-50" @click.self="closeWebtorModal">
      <div class="bg-gray-900 rounded-lg p-6 w-[95vw] h-[95vh] max-w-7xl overflow-auto flex flex-col webtor-modal" @click.stop>
        <!-- Header -->
        <div class="flex justify-between items-center mb-4 flex-shrink-0">
          <h3 class="text-xl font-semibold text-white">Webtor.io Stream</h3>
          <button @click="closeWebtorModal" class="text-white hover:text-red-400 text-2xl">×</button>
        </div>
        
        <!-- Auto-stream Info Section -->
        <div class="mb-4 p-4 bg-gray-800 rounded-lg flex-shrink-0">
          <div class="flex items-center gap-2 mb-2">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-green-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
            <span class="text-green-400 font-medium">Webtor.io SDK Stream Ready</span>
          </div>
          <p class="text-sm text-gray-300">
            Using the official Webtor.io SDK for seamless streaming. Player will load below.
          </p>
          <div class="mt-2 p-2 bg-gray-700 rounded text-xs text-gray-400 font-mono truncate">
            {{ selectedMagnetUri }}
          </div>
        </div>
        
        <!-- Webtor SDK Player -->
        <div class="flex-1 min-h-0 relative overflow-auto">
          <div 
            :id="webtorPlayerId" 
            class="webtor w-full h-full min-h-[400px]"
            :class="{ 'opacity-0': webtorLoading || webtorError }"
            style="touch-action: auto; pointer-events: auto;"
          />
          <!-- Loading overlay when loading -->
          <div v-if="webtorLoading" class="absolute inset-0 flex items-center justify-center bg-gray-900 pointer-events-none">
            <div class="text-center pointer-events-auto">
              <div class="loading loading-spinner loading-lg text-red-600 mb-4"></div>
              <p class="text-white">Loading Webtor player...</p>
            </div>
          </div>
          <!-- Error overlay when error -->
          <div v-else-if="webtorError" class="absolute inset-0 flex items-center justify-center bg-gray-900 pointer-events-none">
            <div class="text-center text-white max-w-md pointer-events-auto">
              <div class="text-red-500 text-6xl mb-4">⚠️</div>
              <h3 class="text-lg font-semibold text-red-400 mb-2">Player Error</h3>
              <p class="text-gray-300 mb-4">{{ webtorError }}</p>
              <div class="space-x-2">
                <button 
                  @click="retryWebtor"
                  class="bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded"
                >
                  Retry
                </button>
                <button 
                  @click="openWebtorInNewTab"
                  class="bg-green-600 hover:bg-green-700 text-white px-4 py-2 rounded"
                >
                  Open in Webtor.io
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div v-if="torrentStore.loading && torrentStore.titleSearchLoading" class="flex justify-center my-8">
      <div class="flex flex-col items-center">
        <span class="loading loading-spinner loading-lg text-red-600 mb-2"></span>
        <p>Searching multiple torrent sources...</p>
      </div>
    </div>
    
    <div v-else-if="torrentStore.magnetLoading" class="flex justify-center my-8">
      <div class="flex flex-col items-center">
        <span class="loading loading-spinner loading-md text-red-600 mb-2"></span>
        <p>Fetching magnet link for {{ torrentStore.selectedTorrent?.name }}...</p>
      </div>
    </div>
    
    <div v-else-if="torrentStore.connectionError" class="alert alert-warning shadow-lg mb-4">
      <div>
        <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current flex-shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
        </svg>
        <div>
          <span class="font-bold">Connection issue</span>
          <p class="text-sm mt-1">{{ torrentStore.error }}</p>
          <div class="mt-3" v-if="torrentStore.downloadSuccess">
            <p class="text-success">Download started successfully.</p>
          </div>
        </div>
      </div>
    </div>
    
    <div v-else-if="torrentStore.downloadSuccess" class="alert alert-success shadow-lg mb-4">
      <div>
        <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current flex-shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
        </svg>
        <span>Download started successfully!</span>
      </div>
    </div>
    
    <div v-else>
      <!-- Title-based Results Section - Now First -->
      <div class="mb-8">
        <div class="flex items-center mb-4">
          <h3 class="text-lg font-semibold">BitSearch Results</h3>
          <div class="badge badge-neutral ml-3">Title based</div>
          <div v-if="torrentStore.titleSearchLoading" class="ml-auto">
            <span class="loading loading-spinner loading-sm text-red-600"></span>
          </div>
        </div>
        
        <div v-if="torrentStore.titleSearchError" class="alert alert-warning mb-6">
          <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
          </svg>
          <span>{{ torrentStore.titleSearchError }}</span>
        </div>
        
        <div v-if="torrentStore.titleSearchResults.length > 0" class="overflow-x-auto mb-6">
          <table class="table w-full">
            <thead>
              <tr>
                <th>Name</th>
                <th>Size</th>
                <th>Seeders</th>
                <th>Source</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
              <tr v-for="torrent in torrentStore.titleSearchResults" :key="torrent.name" class="hover">
                <td class="max-w-md truncate">{{ torrent.name }}</td>
                <td>{{ torrent.size }}</td>
                <td>
                  <span :class="{'text-success': torrent.seeders > 20, 'text-warning': torrent.seeders > 5 && torrent.seeders <= 20, 'text-error': torrent.seeders <= 5}">
                    {{ torrent.seeders }}
                  </span>
                </td>
                <td>
                  <span class="badge badge-sm">{{ torrent.source }}</span>
                </td>
                <td>
                  <div class="flex gap-2">
                    <button @click="openWebtor(torrent)" 
                            class="btn btn-sm bg-purple-600 hover:bg-purple-700 border-purple-700 text-white">
                      <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 12a9 9 0 01-9 9m9-9a9 9 0 00-9-9m9 9H3m9 0l3-3m-3 3l3 3" />
                      </svg>
                      Webtor
                    </button>
                    <button @click="streamTorrent(torrent)" 
                            class="btn btn-sm bg-green-600 hover:bg-green-700 border-green-700 text-white">
                      <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M14.828 14.828a4 4 0 01-5.656 0M9 10h1m4 0h1m-6 4h1m4 0h1m2-7a9 9 0 11-18 0 9 9 0 0118 0z" />
                      </svg>
                      Stream
                    </button>
                    <button @click="downloadTorrent(torrent)" 
                            class="btn btn-sm bg-red-600 hover:bg-red-700 border-red-700 text-white">
                      <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                      </svg>
                      Download
                    </button>
                  </div>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
        
        <div v-else-if="!torrentStore.titleSearchLoading" class="text-center mb-6 py-6 bg-neutral-800/50 rounded-lg">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-12 w-12 mx-auto text-neutral-500 mb-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M9.75 17L9 20l-1 1h8l-1-1-.75-3M3 13h18M5 17h14a2 2 0 002-2V5a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
          </svg>
          <p class="text-neutral-400">No alternative torrents found for this title.</p>
        </div>
      </div>
      
      <!-- IMDB-based Results Section - Now Second -->
      <div class="mt-10 mb-8">
        <div class="flex items-center mb-4">
          <h3 class="text-lg font-semibold">TorrentIO Results</h3>
          <div class="badge badge-neutral ml-3">IMDB ID based</div>
          <div v-if="torrentStore.loading" class="ml-auto">
            <span class="loading loading-spinner loading-sm text-red-600"></span>
          </div>
        </div>
        
        <div v-if="torrentStore.error" class="alert alert-warning mb-6">
          <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
          </svg>
          <span>{{ torrentStore.error }}</span>
        </div>
        
        <div v-if="torrentStore.searchResults.length > 0" class="overflow-x-auto mb-6">
          <table class="table w-full">
            <thead>
              <tr>
                <th>Name</th>
                <th>Size</th>
                <th>Seeders</th>
                <th>Leechers</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
              <tr v-for="torrent in torrentStore.searchResults" :key="torrent.name" class="hover">
                <td class="max-w-md truncate">{{ torrent.name }}</td>
                <td>{{ torrent.size }}</td>
                <td>
                  <span :class="{'text-success': torrent.seeders > 20, 'text-warning': torrent.seeders > 5 && torrent.seeders <= 20, 'text-error': torrent.seeders <= 5}">
                    {{ torrent.seeders }}
                  </span>
                </td>
                <td>{{ torrent.leechers }}</td>
                <td>
                  <div class="flex gap-2">
                    <button @click="openWebtor(torrent)" 
                            class="btn btn-sm bg-purple-600 hover:bg-purple-700 border-purple-700 text-white">
                      <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 12a9 9 0 01-9 9m9-9a9 9 0 00-9-9m9 9H3m9 0l3-3m-3 3l3 3" />
                      </svg>
                      Webtor
                    </button>
                    <button @click="streamTorrent(torrent)" 
                            class="btn btn-sm bg-green-600 hover:bg-green-700 border-green-700 text-white">
                      <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M14.828 14.828a4 4 0 01-5.656 0M9 10h1m4 0h1m-6 4h1m4 0h1m2-7a9 9 0 11-18 0 9 9 0 0118 0z" />
                      </svg>
                      Stream
                    </button>
                    <button @click="downloadTorrent(torrent)" 
                            class="btn btn-sm bg-red-600 hover:bg-red-700 border-red-700 text-white">
                      <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                      </svg>
                      Download
                    </button>
                  </div>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
        
        <div v-else-if="!torrentStore.loading" class="text-center mb-6 py-6 bg-neutral-800/50 rounded-lg">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-12 w-12 mx-auto text-neutral-500 mb-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M9.75 17L9 20l-1 1h8l-1-1-.75-3M3 13h18M5 17h14a2 2 0 002-2V5a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
          </svg>
          <p class="text-neutral-400">No torrents found on TorrentIO.</p>
        </div>
      </div>
      
      <div v-if="!torrentStore.loading && !torrentStore.titleSearchLoading && !torrentStore.searchResults.length && !torrentStore.titleSearchResults.length" 
           class="alert alert-error shadow-lg my-8">
        <div>
          <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current flex-shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" />
          </svg>
          <span>No torrents found from any source. Try searching with a different title.</span>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
// Generated by Copilot July 26, 2025
import { useTorrentStore } from '~/stores/torrent'

const props = defineProps<{
  title: string
}>()

const torrentStore = useTorrentStore()

// Torrent streaming state
const showPlayer = ref(false)
const selectedMagnetUri = ref('')

// Webtor modal state
const showWebtorModal = ref(false)
const magnetCopied = ref(false)
const magnetInput = ref<HTMLInputElement>()
const webtorUrl = ref('')
const webtorLoading = ref(false)
const webtorError = ref('')
const webtorPlayerId = ref('')

// Load Webtor SDK script
const loadWebtorSDK = () => {
  return new Promise<void>((resolve, reject) => {
    // Check if SDK is already loaded
    if (typeof window !== 'undefined' && (window as any).webtor) {
      resolve()
      return
    }

    // Try to load from CDN first, then fallback to local package
    const tryLoadFromCDN = () => {
      const script = document.createElement('script')
      script.src = 'https://cdn.jsdelivr.net/npm/@webtor/embed-sdk-js/dist/index.min.js'
      script.charset = 'utf-8'
      script.async = true
      
      script.onload = () => {
        console.log('✅ Webtor SDK loaded successfully from CDN')
        resolve()
      }
      
      script.onerror = () => {
        console.warn('⚠️ CDN blocked, trying local package fallback...')
        document.head.removeChild(script)
        tryLoadFromLocal()
      }
      
      document.head.appendChild(script)
    }

    const tryLoadFromLocal = () => {
      try {
        // Try to import the local package
        import('@webtor/embed-sdk-js/dist/index.min.js').then(() => {
          console.log('✅ Webtor SDK loaded successfully from local package')
          resolve()
        }).catch(() => {
          // Final fallback - create a mock implementation for development
          console.warn('⚠️ Using iframe fallback since SDK is not available')
          useFallbackImplementation()
          resolve()
        })
      } catch (error) {
        console.warn('⚠️ Local package import failed, using fallback')
        useFallbackImplementation()
        resolve()
      }
    }

    const useFallbackImplementation = () => {
      // Create a simple webtor mock that just creates an iframe
      (window as any).webtor = (window as any).webtor || []
      ;(window as any).webtor.push = function(config: any) {
        const element = document.getElementById(config.id)
        if (element) {
          const encodedMagnet = encodeURIComponent(config.magnet)
          const encodedTitle = encodeURIComponent(config.title || 'Movie')
          const iframe = document.createElement('iframe')
          iframe.src = `https://webtor.io/web?magnet=${encodedMagnet}&lang=en&title=${encodedTitle}`
          iframe.style.width = '100%'
          iframe.style.height = '100%'
          iframe.style.border = 'none'
          iframe.style.touchAction = 'auto'
          iframe.style.pointerEvents = 'auto'
          iframe.allowFullscreen = true
          iframe.allow = 'autoplay; encrypted-media; gyroscope; accelerometer; picture-in-picture; fullscreen'
          // Expand sandbox permissions for touch interactions
          iframe.sandbox = 'allow-same-origin allow-scripts allow-popups allow-forms allow-pointer-lock allow-top-navigation allow-modals'
          element.innerHTML = '' // Clear any existing content
          element.appendChild(iframe)
          
          // Simulate ready event
          setTimeout(() => {
            if (config.on) {
              config.on('ready', {})
            }
          }, 2000)
        }
      }
    }

    tryLoadFromCDN()
  })
}

onMounted(() => {
  initSearch()
})

onUnmounted(() => {
  // Reset state when component is removed from DOM
  torrentStore.resetSearchState()
})

// Watch for title changes to handle navigation between different movies
watch(() => props.title, (newTitle, oldTitle) => {
  if (newTitle !== oldTitle) {
    console.log('Movie changed, searching new torrents for:', newTitle)
    initSearch()
  }
}, { immediate: true })

function initSearch() {
  if (props.title) {
    torrentStore.searchTorrents(props.title)
  }
}

function downloadTorrent(torrent: any) {
  torrentStore.downloadTorrent(torrent)
}

async function streamTorrent(torrent: any) {
  try {
    // Get magnet URI from the torrent
    let magnetUri = ''
    
    if (torrent.magnet) {
      magnetUri = torrent.magnet
    } else if (torrent.magnetLink) {
      magnetUri = torrent.magnetLink
    } else if (torrent.infoHash) {
      magnetUri = `magnet:?xt=urn:btih:${torrent.infoHash}&dn=${encodeURIComponent(torrent.name)}`
    } else {
      // Try to get magnet link via the store
      await torrentStore.getMagnetLink(torrent)
      magnetUri = torrentStore.currentMagnet
    }
    
    if (!magnetUri) {
      throw new Error('Could not obtain magnet URI for this torrent')
    }
    
    selectedMagnetUri.value = magnetUri
    showPlayer.value = true
  } catch (error) {
    console.error('Error starting stream:', error)
    // You might want to show a toast notification here
    alert('Failed to start streaming: ' + (error as Error).message)
  }
}

function closePlayer() {
  showPlayer.value = false
  selectedMagnetUri.value = ''
}

async function openWebtor(torrent: any) {
  try {
    // Get magnet URI from the torrent
    let magnetUri = ''
    
    if (torrent.magnet) {
      magnetUri = torrent.magnet
    } else if (torrent.magnetLink) {
      magnetUri = torrent.magnetLink
    } else if (torrent.infoHash) {
      magnetUri = `magnet:?xt=urn:btih:${torrent.infoHash}&dn=${encodeURIComponent(torrent.name)}`
    } else {
      // Try to get magnet link via the store
      await torrentStore.getMagnetLink(torrent)
      magnetUri = torrentStore.currentMagnet
    }
    
    if (!magnetUri) {
      throw new Error('Could not obtain magnet URI for this torrent')
    }
    
    // Extract movie title from magnet URI or torrent name
    let movieTitle = torrent.name || 'Movie'
    const dnMatch = magnetUri.match(/dn=([^&]+)/)
    if (dnMatch) {
      movieTitle = decodeURIComponent(dnMatch[1].replace(/\+/g, ' '))
    }
    
    selectedMagnetUri.value = magnetUri
    showWebtorModal.value = true
    magnetCopied.value = false
    webtorLoading.value = true
    webtorError.value = ''
    webtorPlayerId.value = `webtor-downloader-${Date.now()}`
    
    // Create fallback URL for "Open in Webtor.io" button
    const encodedMagnet = encodeURIComponent(magnetUri)
    const encodedTitle = encodeURIComponent(movieTitle)
    webtorUrl.value = `https://webtor.io/web?magnet=${encodedMagnet}&lang=en&title=${encodedTitle}`
    
    try {
      // Load the Webtor SDK
      await loadWebtorSDK()
      
      // Wait for DOM to be ready
      await nextTick()
      
      // Initialize Webtor player
      if (typeof window !== 'undefined' && (window as any).webtor) {
        const webtor = (window as any).webtor = (window as any).webtor || []
        
        const playerConfig = {
          id: webtorPlayerId.value,
          magnet: magnetUri,
          title: movieTitle,
          width: '100%',
          height: '100%',
          lang: 'en',
          controls: true,
          header: true,
          on: (event: string, data: any) => {
            console.log('🎮 Webtor downloader event:', event, data)
            
            switch (event) {
              case 'ready':
                webtorLoading.value = false
                break
              case 'error':
                console.error('❌ Webtor downloader error:', data)
                webtorError.value = data.message || 'Player error occurred'
                webtorLoading.value = false
                break
            }
          }
        }
        
        console.log('🔧 Webtor downloader config:', playerConfig)
        webtor.push(playerConfig)
        
        // Set a timeout to handle cases where the player doesn't respond
        setTimeout(() => {
          if (webtorLoading.value) {
            console.log('⏰ Webtor player setup timeout, considering ready')
            webtorLoading.value = false
          }
        }, 10000)
        
      } else {
        throw new Error('Webtor SDK not available')
      }
      
    } catch (sdkError) {
      console.error('❌ Webtor SDK error:', sdkError)
      webtorError.value = 'Failed to load Webtor player. This might be due to network issues.'
      webtorLoading.value = false
    }
    
  } catch (error) {
    console.error('Error opening Webtor:', error)
    alert('Failed to get magnet link: ' + (error as Error).message)
  }
}

function closeWebtorModal() {
  showWebtorModal.value = false
  selectedMagnetUri.value = ''
  magnetCopied.value = false
  webtorUrl.value = ''
  webtorLoading.value = false
  webtorError.value = ''
  
  // Cleanup the player
  if (webtorPlayerId.value) {
    const playerElement = document.getElementById(webtorPlayerId.value)
    if (playerElement) {
      playerElement.innerHTML = ''
    }
    webtorPlayerId.value = ''
  }
}

function retryWebtor() {
  webtorLoading.value = true
  webtorError.value = ''
  
  // Retry initialization
  const currentMagnet = selectedMagnetUri.value
  const currentTitle = webtorUrl.value.match(/title=([^&]+)/)?.[1] || 'Movie'
  
  setTimeout(async () => {
    try {
      await loadWebtorSDK()
      await nextTick()
      
      if (typeof window !== 'undefined' && (window as any).webtor) {
        const webtor = (window as any).webtor = (window as any).webtor || []
        
        const playerConfig = {
          id: webtorPlayerId.value,
          magnet: currentMagnet,
          title: decodeURIComponent(currentTitle),
          width: '100%',
          height: '100%',
          lang: 'en',
          controls: true,
          header: true,
          on: (event: string, data: any) => {
            console.log('🎮 Webtor retry event:', event, data)
            
            switch (event) {
              case 'ready':
                webtorLoading.value = false
                break
              case 'error':
                console.error('❌ Webtor retry error:', data)
                webtorError.value = data.message || 'Player error occurred'
                webtorLoading.value = false
                break
            }
          }
        }
        
        webtor.push(playerConfig)
        
        setTimeout(() => {
          if (webtorLoading.value) {
            webtorLoading.value = false
          }
        }, 10000)
        
      } else {
        throw new Error('Webtor SDK not available')
      }
    } catch (error) {
      webtorError.value = 'Failed to retry Webtor player'
      webtorLoading.value = false
    }
  }, 1000)
}

function openWebtorInNewTab() {
  if (webtorUrl.value) {
    window.open(webtorUrl.value, '_blank')
  }
}

function selectMagnetText() {
  if (magnetInput.value) {
    magnetInput.value.select()
    magnetInput.value.setSelectionRange(0, 99999) // For mobile devices
  }
}

async function copyMagnetToClipboard() {
  try {
    await navigator.clipboard.writeText(selectedMagnetUri.value)
    magnetCopied.value = true
    
    // Reset copied status after 3 seconds
    setTimeout(() => {
      magnetCopied.value = false
    }, 3000)
  } catch (error) {
    console.error('Failed to copy magnet link:', error)
    // Fallback: select text for manual copy
    selectMagnetText()
    
    // Try document.execCommand as fallback
    try {
      document.execCommand('copy')
      magnetCopied.value = true
      setTimeout(() => {
        magnetCopied.value = false
      }, 3000)
    } catch (fallbackError) {
      alert('Please manually copy the magnet link')
    }
  }
}
</script>

<style scoped>
.webtor-modal {
  /* Enable smooth scrolling on iOS Safari */
  -webkit-overflow-scrolling: touch;
  /* Ensure proper scroll behavior on mobile */
  overscroll-behavior: contain;
}

/* Mobile-specific improvements */
@media (max-width: 768px) {
  .webtor-modal {
    /* On mobile, make modal take full height and allow scrolling */
    height: 100vh;
    width: 100vw;
    border-radius: 0;
    /* Improve touch scrolling performance */
    -webkit-overflow-scrolling: touch;
    transform: translate3d(0, 0, 0);
  }
}

/* Ensure webtor iframe can be scrolled and receive touch events */
.webtor {
  /* Allow content to be scrollable */
  overflow: auto !important;
  -webkit-overflow-scrolling: touch;
  /* Ensure touch events reach the iframe */
  touch-action: auto !important;
  pointer-events: auto !important;
}

.webtor iframe {
  /* Ensure iframe receives touch events */
  touch-action: auto !important;
  pointer-events: auto !important;
}
</style>