<!-- Generated by Copilot April 25, 2025 20:45 -->
<template>
  <div>
    <div v-if="torrentStore.loading && torrentStore.titleSearchLoading" class="flex justify-center my-8">
      <div class="flex flex-col items-center">
        <span class="loading loading-spinner loading-lg text-red-600 mb-2"></span>
        <p>Searching multiple torrent sources...</p>
      </div>
    </div>
    
    <div v-else-if="torrentStore.magnetLoading" class="flex justify-center my-8">
      <div class="flex flex-col items-center">
        <span class="loading loading-spinner loading-md text-red-600 mb-2"></span>
        <p>Fetching magnet link for {{ torrentStore.selectedTorrent?.name }}...</p>
      </div>
    </div>
    
    <div v-else-if="torrentStore.connectionError" class="alert alert-warning shadow-lg mb-4">
      <div>
        <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current flex-shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
        </svg>
        <div>
          <span class="font-bold">Connection issue</span>
          <p class="text-sm mt-1">{{ torrentStore.error }}</p>
          <div class="mt-3" v-if="torrentStore.downloadSuccess">
            <p class="text-success">Download started successfully.</p>
          </div>
        </div>
      </div>
    </div>
    
    <div v-else-if="torrentStore.downloadSuccess" class="alert alert-success shadow-lg mb-4">
      <div>
        <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current flex-shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
        </svg>
        <span>Download started successfully!</span>
      </div>
    </div>
    
    <div v-else>
      <!-- Title-based Results Section - Now First -->
      <div class="mb-8">
        <div class="flex items-center mb-4">
          <h3 class="text-lg font-semibold">BitSearch Results</h3>
          <div class="badge badge-neutral ml-3">Title based</div>
          <div v-if="torrentStore.titleSearchLoading" class="ml-auto">
            <span class="loading loading-spinner loading-sm text-red-600"></span>
          </div>
        </div>
        
        <div v-if="torrentStore.titleSearchError" class="alert alert-warning mb-6">
          <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
          </svg>
          <span>{{ torrentStore.titleSearchError }}</span>
        </div>
        
        <div v-if="torrentStore.titleSearchResults.length > 0" class="overflow-x-auto mb-6">
          <table class="table w-full">
            <thead>
              <tr>
                <th>Name</th>
                <th>Size</th>
                <th>Seeders</th>
                <th>Source</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
              <tr v-for="torrent in torrentStore.titleSearchResults" :key="torrent.name" class="hover">
                <td class="max-w-md truncate">{{ torrent.name }}</td>
                <td>{{ torrent.size }}</td>
                <td>
                  <span :class="{'text-success': torrent.seeders > 20, 'text-warning': torrent.seeders > 5 && torrent.seeders <= 20, 'text-error': torrent.seeders <= 5}">
                    {{ torrent.seeders }}
                  </span>
                </td>
                <td>
                  <span class="badge badge-sm">{{ torrent.source }}</span>
                </td>
                <td>
                  <button @click="downloadTorrent(torrent)" 
                          class="btn btn-sm bg-red-600 hover:bg-red-700 border-red-700 text-white">Download</button>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
        
        <div v-else-if="!torrentStore.titleSearchLoading" class="text-center mb-6 py-6 bg-neutral-800/50 rounded-lg">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-12 w-12 mx-auto text-neutral-500 mb-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M9.75 17L9 20l-1 1h8l-1-1-.75-3M3 13h18M5 17h14a2 2 0 002-2V5a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
          </svg>
          <p class="text-neutral-400">No alternative torrents found for this title.</p>
        </div>
      </div>
      
      <!-- IMDB-based Results Section - Now Second -->
      <div class="mt-10 mb-8">
        <div class="flex items-center mb-4">
          <h3 class="text-lg font-semibold">TorrentIO Results</h3>
          <div class="badge badge-neutral ml-3">IMDB ID based</div>
          <div v-if="torrentStore.loading" class="ml-auto">
            <span class="loading loading-spinner loading-sm text-red-600"></span>
          </div>
        </div>
        
        <div v-if="torrentStore.error" class="alert alert-warning mb-6">
          <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
          </svg>
          <span>{{ torrentStore.error }}</span>
        </div>
        
        <div v-if="torrentStore.searchResults.length > 0" class="overflow-x-auto mb-6">
          <table class="table w-full">
            <thead>
              <tr>
                <th>Name</th>
                <th>Size</th>
                <th>Seeders</th>
                <th>Leechers</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
              <tr v-for="torrent in torrentStore.searchResults" :key="torrent.name" class="hover">
                <td class="max-w-md truncate">{{ torrent.name }}</td>
                <td>{{ torrent.size }}</td>
                <td>
                  <span :class="{'text-success': torrent.seeders > 20, 'text-warning': torrent.seeders > 5 && torrent.seeders <= 20, 'text-error': torrent.seeders <= 5}">
                    {{ torrent.seeders }}
                  </span>
                </td>
                <td>{{ torrent.leechers }}</td>
                <td>
                  <button @click="downloadTorrent(torrent)" 
                          class="btn btn-sm bg-red-600 hover:bg-red-700 border-red-700 text-white">Download</button>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
        
        <div v-else-if="!torrentStore.loading" class="text-center mb-6 py-6 bg-neutral-800/50 rounded-lg">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-12 w-12 mx-auto text-neutral-500 mb-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M9.75 17L9 20l-1 1h8l-1-1-.75-3M3 13h18M5 17h14a2 2 0 002-2V5a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
          </svg>
          <p class="text-neutral-400">No torrents found on TorrentIO.</p>
        </div>
      </div>
      
      <div v-if="!torrentStore.loading && !torrentStore.titleSearchLoading && !torrentStore.searchResults.length && !torrentStore.titleSearchResults.length" 
           class="alert alert-error shadow-lg my-8">
        <div>
          <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current flex-shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" />
          </svg>
          <span>No torrents found from any source. Try searching with a different title.</span>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { useTorrentStore } from '~/stores/torrent'

const props = defineProps<{
  title: string
}>()

const torrentStore = useTorrentStore()

onMounted(() => {
  initSearch()
})

onUnmounted(() => {
  // Reset state when component is removed from DOM
  torrentStore.resetSearchState()
})

// Watch for title changes to handle navigation between different movies
watch(() => props.title, (newTitle, oldTitle) => {
  if (newTitle !== oldTitle) {
    console.log('Movie changed, searching new torrents for:', newTitle)
    initSearch()
  }
}, { immediate: true })

function initSearch() {
  if (props.title) {
    torrentStore.searchTorrents(props.title)
  }
}

function downloadTorrent(torrent: any) {
  torrentStore.downloadTorrent(torrent)
}
</script>