<!-- Generated by Copilot April 27, 2025 15:35 -->
<template>
  <div>
    <div v-if="loading" class="flex justify-center my-12">
      <span class="loading loading-spinner loading-lg text-red-600"></span>
    </div>
    
    <div v-else-if="error" class="container mx-auto p-4">
      <div class="alert alert-error shadow-lg mb-4">
        <div>
          <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current flex-shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" />
          </svg>
          <span>{{ error }}</span>
        </div>
      </div>
    </div>
    
    <div v-else>
      <!-- Hero Section with Backdrop -->
      <div 
        class="w-full h-[50vh] bg-cover bg-center relative"
        :style="{ backgroundImage: `url(${backdropUrl})` }"
      >
        <div class="absolute inset-0 bg-gradient-to-t from-neutral-900 to-transparent"></div>
        
        <!-- Back Button -->
        <div class="absolute top-4 left-4 z-20">
          <button 
            @click="goBack"
            class="btn btn-circle btn-ghost bg-black/50 hover:bg-black/70 text-white border-0 backdrop-blur-sm transition-all duration-200"
            title="Go back"
          >
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7" />
            </svg>
          </button>
        </div>

        <!-- Favorite Button -->
        <div class="absolute top-4 right-4 z-20">
          <button
            @click="toggleFavorite"
            class="btn btn-circle btn-ghost bg-black/50 hover:bg-black/70 text-red-500 border-0 backdrop-blur-sm transition-all duration-200"
            :title="isFavorite ? 'Remove from favorites' : 'Add to favorites'"
          >
            <svg v-if="isFavorite" xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 fill-current" viewBox="0 0 24 24">
              <path fill-rule="evenodd" d="M3.172 5.172a4 4 0 015.656 0L12 8.343l3.172-3.171a4 4 0 115.656 5.656L12 21.657l-8.828-8.829a4 4 0 010-5.656z" clip-rule="evenodd" />
            </svg>
            <svg v-else xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3.172 5.172a4 4 0 015.656 0L12 8.343l3.172-3.171a4 4 0 115.656 5.656L12 21.657l-8.828-8.829a4 4 0 010-5.656z" />
            </svg>
          </button>
        </div>
        
        <div class="container mx-auto p-4 flex items-end h-full relative z-10">
          <div class="flex flex-col md:flex-row items-end md:items-center gap-6">
            <img 
              :src="posterUrl" 
              :alt="movie.title" 
              class="w-32 md:w-48 rounded-lg shadow-xl"
              @error="useDefaultPoster"
            />
            <div>
              <h1 class="text-3xl md:text-4xl font-bold mb-2">{{ movie.title }}</h1>
              <p class="text-sm opacity-70">
                {{ releaseYear }} | 
                <span class="badge badge-accent">{{ formatRating }}</span>
              </p>
            </div>
          </div>
        </div>
      </div>
      
      <!-- Content Section -->
      <div class="container mx-auto p-4">
        <div class="flex flex-col md:flex-row gap-8">
          <!-- Main Content -->
          <div class="md:w-2/3">
            <div class="card bg-neutral-800 mb-8">
              <div class="card-body">
                <h2 class="card-title text-xl mb-2">Overview</h2>
                <p>{{ movie.overview || 'No overview available.' }}</p>
              </div>
            </div>
            
            <!-- Movie Images Gallery Section -->
            <div class="card bg-neutral-800 mb-8">
              <div class="card-body">
                <h2 class="card-title text-xl mb-4">Photo Gallery</h2>
                
                <div v-if="loadingImages" class="flex justify-center my-4">
                  <span class="loading loading-spinner loading-md text-red-600"></span>
                </div>
                
                <div v-else-if="movieImages.length === 0" class="text-center py-6">
                  <svg xmlns="http://www.w3.org/2000/svg" class="h-12 w-12 mx-auto text-neutral-500 mb-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1" d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />
                  </svg>
                  <p class="text-neutral-400">No images available</p>
                </div>
                
                <div v-else>
                  <!-- Gallery Grid -->
                  <div class="grid grid-cols-2 md:grid-cols-3 gap-4 mb-4">
                    <div 
                      v-for="(image, index) in displayedImages" 
                      :key="index"
                      class="aspect-video relative group cursor-pointer overflow-hidden rounded-lg"
                      @click="openImageGallery(index)"
                    >
                      <img 
                        :src="`${config.public.tmdbImageBaseUrl}/w500${image.file_path}`" 
                        :alt="`${movie.title} image ${index + 1}`"
                        class="w-full h-full object-cover transition-transform duration-300 group-hover:scale-110"
                      />
                      <div class="absolute inset-0 bg-black/0 group-hover:bg-black/40 transition-colors flex items-center justify-center">
                        <svg 
                          xmlns="http://www.w3.org/2000/svg" 
                          class="h-8 w-8 text-white opacity-0 group-hover:opacity-100 transition-opacity transform scale-75 group-hover:scale-100"
                          fill="none" 
                          viewBox="0 0 24 24" 
                          stroke="currentColor"
                        >
                          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0zM10 7v3m0 0v3m0-3h3m-3 0H7" />
                        </svg>
                      </div>
                    </div>
                  </div>
                  
                  <!-- Show More Button -->
                  <div v-if="movieImages.length > initialImageCount" class="text-center mt-6">
                    <button 
                      @click="toggleShowAllImages"
                      class="btn btn-outline btn-ghost btn-sm"
                    >
                      {{ showAllImages ? 'Show Less' : `Show All (${movieImages.length})` }}
                    </button>
                  </div>
                </div>
              </div>
            </div>
            
            <!-- Movie Trailer Section -->
            <div v-if="trailerKey" class="card bg-neutral-800 mb-8">
              <div class="card-body">
                <h2 class="card-title text-xl mb-2">Trailer</h2>
                <div class="relative pb-[56.25%] h-0">
                  <iframe 
                    :src="`https://www.youtube.com/embed/${trailerKey}`" 
                    class="absolute top-0 left-0 w-full h-full rounded-lg"
                    frameborder="0"
                    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                    allowfullscreen
                  ></iframe>
                </div>
              </div>
            </div>
            
            <div v-if="watchOptionsVisible" class="card bg-neutral-800 mb-8">
              <div class="card-body">
                <h2 class="card-title text-xl mb-2">Watch Now</h2>
                <p class="mb-4">Stream "{{ movie.title }}" instantly:</p>
                <div class="flex gap-3 flex-wrap">
                  <button @click="watchMovie" class="btn btn-primary">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M14.828 14.828a4 4 0 01-5.656 0M9 10h1m4 0h1m-6 4h1m4 0h1m2-7a9 9 0 11-18 0 9 9 0 0118 0z" />
                    </svg>
                    Watch
                  </button>
                  <button @click="downloadMovie" class="btn btn-outline btn-secondary">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                    </svg>
                    Download Options
                  </button>
                </div>
              </div>
            </div>
          </div>
          
          <!-- Sidebar -->
          <div class="md:w-1/3">
            <div class="card bg-neutral-800 mb-6">
              <div class="card-body">
                <h2 class="card-title text-xl mb-2">Movie Details</h2>
                <div class="overflow-x-auto">
                  <table class="table w-full">
                    <tbody>
                      <tr>
                        <td class="font-bold">Release Date</td>
                        <td @click="handleReleaseDateTap" @touchstart="handleReleaseDateTap">{{ formatDate }}</td>
                      </tr>
                      <tr>
                        <td class="font-bold">Rating</td>
                        <td>{{ movie.vote_average?.toFixed(1) || 'N/A' }}/10 ({{ movie.vote_count }} votes)</td>
                      </tr>
                      <tr>
                        <td class="font-bold">Genres</td>
                        <td>
                          <div class="flex flex-wrap gap-1">
                            <NuxtLink
                              v-for="genre in movie.genres"
                              :key="genre.id"
                              :to="`/genres?id=${genre.id}`"
                              class="badge badge-outline hover:bg-red-600 hover:text-white hover:border-red-700 cursor-pointer transition-colors duration-200"
                            >
                              {{ genre.name }}
                            </NuxtLink>
                          </div>
                        </td>
                      </tr>
                      <tr v-if="directors.length">
                        <td class="font-bold">Director</td>
                        <td>
                          <div class="flex flex-wrap gap-1">
                            <NuxtLink
                              v-for="person in directors"
                              :key="person.id"
                              :to="`/search?q=${encodeURIComponent(person.name)}`"
                              class="badge badge-outline hover:bg-red-600 hover:text-white hover:border-red-700 cursor-pointer transition-colors duration-200"
                            >
                              {{ person.name }}
                            </NuxtLink>
                          </div>
                        </td>
                      </tr>
                      <tr v-if="topCast.length">
                        <td class="font-bold">Cast</td>
                        <td>
                          <div class="flex flex-wrap gap-1">
                            <NuxtLink
                              v-for="actor in topCast"
                              :key="actor.id"
                              :to="`/search?q=${encodeURIComponent(actor.name)}`"
                              class="badge badge-outline hover:bg-red-600 hover:text-white hover:border-red-700 cursor-pointer transition-colors duration-200"
                            >
                              {{ actor.name }}
                            </NuxtLink>
                          </div>
                        </td>
                      </tr>
                      <tr v-if="movie.runtime">
                        <td class="font-bold">Runtime</td>
                        <td>{{ formatRuntime }}</td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
        
        <!-- Related Movies Section -->
        <div class="mt-12 mb-8">
          <div class="flex items-center justify-between mb-6">
            <h2 class="text-2xl md:text-3xl font-bold">
              <span class="text-red-600">Related</span> Movies
            </h2>
            <div class="flex items-center gap-2 text-sm text-neutral-400">
              <!-- Generated by Copilot - April 27, 2025 -->
              <button @click="scrollRelatedMovies('left')" class="btn btn-sm btn-ghost p-1">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7" />
                </svg>
              </button>
              <button @click="scrollRelatedMovies('right')" class="btn btn-sm btn-ghost p-1">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" />
                </svg>
              </button>
            </div>
          </div>
          
          <div v-if="loadingRelated" class="flex justify-center my-8">
            <span class="loading loading-spinner loading-lg text-red-600"></span>
          </div>
          
          <div v-else-if="relatedError" class="alert alert-error shadow-lg mb-4">
            <div>
              <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current flex-shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" />
              </svg>
              <span>{{ relatedError }}</span>
            </div>
          </div>
          
          <div v-else-if="relatedMovies.length === 0" class="text-center my-8 py-8 bg-neutral-800/50 rounded-lg">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-16 w-16 mx-auto text-neutral-500 mb-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1" d="M7 4v16M17 4v16M3 8h4m10 0h4M3 12h18M3 16h4m10 0h4M4 20h16a1 1 0 001-1V5a1 1 0 00-1-1H4a1 1 0 00-1 1v14a1 1 0 001 1z" />
            </svg>
            <p class="text-lg text-neutral-400">No related movies found</p>
          </div>
          
          <div v-else class="relative group">
            <!-- Previous Button -->
            <button 
              v-show="canScrollLeft"
              class="hidden group-hover:flex absolute left-0 top-1/2 -translate-y-1/2 z-10 h-32 px-2 items-center justify-center bg-gradient-to-r from-neutral-900/90 to-neutral-900/0 text-white hover:text-red-600 transition-colors"
              @click="scrollRelatedMovies('left')"
            >
              <svg xmlns="http://www.w3.org/2000/svg" class="h-8 w-8" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7" />
              </svg>
            </button
            
            <!-- Movies Container -->
            <div 
              ref="relatedMoviesContainer"
              class="flex overflow-x-auto pb-6 scrollbar-hide snap-x snap-mandatory"
              @scroll="updateScrollButtons"
            >
              <div 
                v-for="relatedMovie in relatedMovies" 
                :key="relatedMovie.id" 
                class="snap-start w-[180px] md:w-[220px] flex-shrink-0 px-2"
              >
                <MovieCard :movie="relatedMovie" />
              </div>
            </div>
            
            <!-- Next Button -->
            <button 
              v-show="canScrollRight"
              class="hidden group-hover:flex absolute right-0 top-1/2 -translate-y-1/2 z-10 h-32 px-2 items-center justify-center bg-gradient-to-l from-neutral-900/90 to-neutral-900/0 text-white hover:text-red-600 transition-colors"
              @click="scrollRelatedMovies('right')"
            >
              <svg xmlns="http://www.w3.org/2000/svg" class="h-8 w-8" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" />
              </svg>
            </button>
          </div>
        </div>
      </div>
    </div>
    
    <!-- Image Gallery Modal -->
    <ImageGalleryModal
      v-model="showGallery"
      :images="movieImages"
      :base-url="config.public.tmdbImageBaseUrl"
      :initial-index="selectedImageIndex"
    />
    
    <!-- Auto Stream Player -->
    <AutoStreamPlayer
      v-model="showStreamPlayer"
      :movie-title="movie.title"
      :is-visible="showStreamPlayer"
      @close="closeStreamPlayer"
    />
  </div>
</template>

<script setup lang="ts">
import axios from 'axios'
import type { Movie } from '~/types/movie'
import { useFavoritesStore } from '~/stores/favorites'
// Generated by Copilot - April 27, 2025 15:54
// Define MovieDetail interface inline instead of importing it
interface MovieDetail {
  id: number
  title: string
  poster_path: string
  backdrop_path: string
  overview: string
  release_date: string
  vote_average: number
  vote_count: number
  genres: { id: number, name: string }[]
  runtime: number
  belongs_to_collection?: {
    id: number
    name: string
    poster_path: string
    backdrop_path: string
  }
}

// Define MovieImage interface for the gallery
interface MovieImage {
  file_path: string
  width: number
  height: number
  aspect_ratio: number
}

interface Person {
  id: number
  name: string
}

const route = useRoute()
const router = useRouter()
const config = useRuntimeConfig()
const favoritesStore = useFavoritesStore()

const movieId = computed(() => route.params.id as string)
const movie = ref<MovieDetail>({} as MovieDetail)
const loading = ref(true)
const error = ref<string | null>(null)
const trailerKey = ref<string | null>(null)

// Movie images state
const movieImages = ref<MovieImage[]>([])
const loadingImages = ref(true)

// Related movies state
const relatedMovies = ref<Movie[]>([])
const loadingRelated = ref(true)
const relatedError = ref<string | null>(null)

// Credits state
const directors = ref<Person[]>([])
const topCast = ref<Person[]>([])

const watchOptionsVisible = ref(false)
const releaseDateTapCount = ref(0)

const isFavorite = computed(() => favoritesStore.isFavorite(movie.value.id))

function toggleFavorite() {
  if (!movie.value) return
  favoritesStore.toggleFavorite({
    id: movie.value.id,
    title: movie.value.title,
    poster_path: movie.value.poster_path,
    overview: movie.value.overview,
    release_date: movie.value.release_date,
    vote_average: movie.value.vote_average
  })
}


const posterUrl = computed(() => {
  if (!movie.value.poster_path) return '/no-poster.jpg'
  return `${config.public.tmdbImageBaseUrl}/w500${movie.value.poster_path}`
})

const backdropUrl = computed(() => {
  if (!movie.value.backdrop_path) return ''
  return `${config.public.tmdbImageBaseUrl}/original${movie.value.backdrop_path}`
})

const formatRating = computed(() => {
  return movie.value.vote_average?.toFixed(1) || 'N/A'
})

const releaseYear = computed(() => {
  if (!movie.value.release_date) return 'Unknown year'
  return new Date(movie.value.release_date).getFullYear()
})

const formatDate = computed(() => {
  if (!movie.value.release_date) return 'Unknown date'
  return new Date(movie.value.release_date).toLocaleDateString()
})

const formatRuntime = computed(() => {
  if (!movie.value.runtime) return 'Unknown'
  const hours = Math.floor(movie.value.runtime / 60)
  const minutes = movie.value.runtime % 60
  return `${hours}h ${minutes}m`
})

// Gallery state
const initialImageCount = 6
const showAllImages = ref(false)
const showGallery = ref(false)
const selectedImageIndex = ref(0)

// Auto Stream Player state
const showStreamPlayer = ref(false)

// Display limited images initially
const displayedImages = computed(() => {
  return showAllImages.value 
    ? movieImages.value 
    : movieImages.value.slice(0, initialImageCount)
})

function useDefaultPoster(event: Event) {
  const target = event.target as HTMLImageElement
  target.src = '/no-poster.jpg'
}

function downloadMovie() {
  router.push(`/download/${movie.value.id}`)
}

function watchMovie() {
  console.log('🎬 Starting watch for:', movie.value.title)
  showStreamPlayer.value = true
}

function closeStreamPlayer() {
  console.log('🚪 Closing stream player')
  showStreamPlayer.value = false
}

function goBack() {
  router.back()
}

function toggleShowAllImages() {
  showAllImages.value = !showAllImages.value
}

function openImageGallery(index: number) {
  selectedImageIndex.value = index
  showGallery.value = true
}

function handleReleaseDateTap() {
  if (watchOptionsVisible.value) return
  releaseDateTapCount.value++
  if (releaseDateTapCount.value >= 3) {
    watchOptionsVisible.value = true
    releaseDateTapCount.value = 0
  }
  setTimeout(() => {
    releaseDateTapCount.value = 0
  }, 1000)
}

// Related movies scroll state
const relatedMoviesContainer = ref<HTMLElement | null>(null)
const canScrollLeft = ref(false)
const canScrollRight = ref(false)

function updateScrollButtons() {
  if (!relatedMoviesContainer.value) return
  
  const container = relatedMoviesContainer.value
  canScrollLeft.value = container.scrollLeft > 0
  canScrollRight.value = container.scrollLeft < container.scrollWidth - container.clientWidth
}

function scrollRelatedMovies(direction: 'left' | 'right') {
  if (!relatedMoviesContainer.value) return
  
  const container = relatedMoviesContainer.value
  const scrollAmount = container.clientWidth * 0.8
  
  container.scrollBy({
    left: direction === 'left' ? -scrollAmount : scrollAmount,
    behavior: 'smooth'
  })
}

// Generated by Copilot - April 27, 2025 15:54
// Handle keyboard navigation for related movies
function handleKeyDown(e: KeyboardEvent) {
  if (!showGallery.value) { // Only handle when gallery is not open
    if (e.key === 'ArrowLeft') {
      scrollRelatedMovies('left')
    } else if (e.key === 'ArrowRight') {
      scrollRelatedMovies('right')
    }
  }
}

onMounted(() => {
  window.addEventListener('keydown', handleKeyDown)
})

onUnmounted(() => {
  window.removeEventListener('keydown', handleKeyDown)
})

async function fetchMovieImages(movieId: string) {
  loadingImages.value = true
  
  try {
    const response = await axios.get(`${config.public.tmdbApiBaseUrl}/movie/${movieId}/images`, {
      params: {
        api_key: config.public.tmdbApiKey,
        include_image_language: 'en,null'
      }
    })
    
    // Get backdrops and stills, sort by vote average
    const allImages = [
      ...(response.data.backdrops || []),
      ...(response.data.stills || [])
    ]
    
    // Sort by vote count (popularity) and take up to 15 images
    movieImages.value = allImages
      .sort((a: any, b: any) => b.vote_count - a.vote_count)
      .slice(0, 15)
  } catch (err: any) {
    console.error('Error fetching movie images:', err)
  } finally {
    loadingImages.value = false
  }
}

async function fetchRelatedMovies(movieId: string) {
  loadingRelated.value = true
  relatedError.value = null
  
  try {
    let collectionMovies: Movie[] = []
    let relatedMoviesList: Movie[] = []
    
    // First, check if this movie belongs to a collection
    if (movie.value.belongs_to_collection?.id) {
      try {
        const collectionResponse = await axios.get(`${config.public.tmdbApiBaseUrl}/collection/${movie.value.belongs_to_collection.id}`, {
          params: {
            api_key: config.public.tmdbApiKey,
            language: 'en-US'
          }
        })
        
        // Get movies from collection, excluding the current movie
        collectionMovies = collectionResponse.data.parts
          .filter((movie: Movie) => movie.id !== parseInt(movieId) && movie.poster_path)
          .sort((a: Movie, b: Movie) => new Date(a.release_date).getTime() - new Date(b.release_date).getTime())
      } catch (collectionErr) {
        console.error('Error fetching collection movies:', collectionErr)
      }
    }
    
    // If we have collection movies, prioritize them
    if (collectionMovies.length > 0) {
      relatedMoviesList = [...collectionMovies]
      
      // If we don't have enough collection movies (less than 6), fill with similar movies
      if (collectionMovies.length < 6) {
        try {
          const similarResponse = await axios.get(`${config.public.tmdbApiBaseUrl}/movie/${movieId}/similar`, {
            params: {
              api_key: config.public.tmdbApiKey,
              language: 'en-US',
              page: 1
            }
          })
          
          const similarMovies = similarResponse.data.results
            .filter((movie: Movie) => movie.poster_path)
            // Exclude movies already in collection
            .filter((movie: Movie) => !collectionMovies.some(colMovie => colMovie.id === movie.id))
            .slice(0, 10 - collectionMovies.length)
          
          relatedMoviesList = [...collectionMovies, ...similarMovies]
        } catch (similarErr) {
          console.error('Error fetching similar movies to supplement collection:', similarErr)
          relatedMoviesList = collectionMovies
        }
      }
    } else {
      // Fall back to similar movies if no collection
      const response = await axios.get(`${config.public.tmdbApiBaseUrl}/movie/${movieId}/similar`, {
        params: {
          api_key: config.public.tmdbApiKey,
          language: 'en-US',
          page: 1
        }
      })
      
      relatedMoviesList = response.data.results
        .filter((movie: Movie) => movie.poster_path)
    }
    
    // Limit to 10 movies total
    relatedMovies.value = relatedMoviesList.slice(0, 10)
  } catch (err: any) {
    relatedError.value = "Failed to load related movies"
    console.error('Error fetching related movies:', err)
  } finally {
    loadingRelated.value = false
  }
}

async function fetchTrailer() {
  try {
    const youtubeApiKey = 'AIzaSyBvjdSskE5mjasc3Ptit5k_ZACwxVPWCNU'
    
    // First try to get the trailer from TMDB videos endpoint
    const tmdbResponse = await axios.get(`${config.public.tmdbApiBaseUrl}/movie/${movieId.value}/videos`, {
      params: {
        api_key: config.public.tmdbApiKey
      }
    })
    
    const videos = tmdbResponse.data.results || []
    
    // Look for an official trailer
    const trailer = videos.find((video: any) => 
      (video.type === 'Trailer' || video.type === 'Teaser') && 
      video.site === 'YouTube'
    )
    
    if (trailer) {
      trailerKey.value = trailer.key
      return
    }
    
    // If no trailer found in TMDB, try YouTube API directly
    const query = `${movie.value.title} ${releaseYear.value} trailer official`
    const youtubeResponse = await axios.get('https://www.googleapis.com/youtube/v3/search', {
      params: {
        part: 'snippet',
        maxResults: 1,
        q: query,
        type: 'video',
        videoEmbeddable: true,
        key: youtubeApiKey
      }
    })
    
    if (youtubeResponse.data.items && youtubeResponse.data.items.length > 0) {
      trailerKey.value = youtubeResponse.data.items[0].id.videoId
    }
  } catch (err) {
    console.error('Error fetching trailer:', err)
  }
}

onMounted(async () => {
  try {
    loading.value = true
    error.value = null
    
    const response = await axios.get(`${config.public.tmdbApiBaseUrl}/movie/${movieId.value}`, {
      params: {
        api_key: config.public.tmdbApiKey,
        append_to_response: 'credits'
      }
    })

    movie.value = response.data

    // Extract director(s) and top cast from credits
    const credits = response.data.credits || {}
    directors.value = (credits.crew || [])
      .filter((c: any) => c.job === 'Director')
      .map((c: any) => ({ id: c.id, name: c.name }))
    topCast.value = (credits.cast || [])
      .slice(0, 5)
      .map((c: any) => ({ id: c.id, name: c.name }))

    // Fetch trailer after movie details are loaded
    await fetchTrailer()

    // Fetch movie images for gallery
    await fetchMovieImages(movieId.value)

    // Fetch related movies
    await fetchRelatedMovies(movieId.value)
  } catch (err: any) {
    error.value = err.message || 'Failed to load movie'
  } finally {
    loading.value = false
  }
})
</script>

<style scoped>
.scrollbar-hide {
  -ms-overflow-style: none;
  scrollbar-width: none;
}
.scrollbar-hide::-webkit-scrollbar {
  display: none;
}

/* Fade edges of movie cards */
.movie-list-fade {
  mask-image: linear-gradient(to right, transparent, black 5%, black 95%, transparent);
  -webkit-mask-image: linear-gradient(to right, transparent, black 5%, black 95%, transparent);
}
</style>
