<!-- Generated by Copilot 2025-04-23 14:40 -->
<template>
  <div>
    <div v-if="loading" class="flex justify-center my-12">
      <span class="loading loading-spinner loading-lg text-red-600"></span>
    </div>
    
    <div v-else-if="error" class="container mx-auto p-4">
      <div class="alert alert-error shadow-lg mb-4">
        <div>
          <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current flex-shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" />
          </svg>
          <span>{{ error }}</span>
        </div>
      </div>
    </div>
    
    <div v-else>
      <!-- Hero Section with Backdrop -->
      <div 
        class="w-full h-[50vh] bg-cover bg-center relative"
        :style="{ backgroundImage: `url(${backdropUrl})` }"
      >
        <div class="absolute inset-0 bg-gradient-to-t from-neutral-900 to-transparent"></div>
        <div class="container mx-auto p-4 flex items-end h-full relative z-10">
          <div class="flex flex-col md:flex-row items-end md:items-center gap-6">
            <img 
              :src="posterUrl" 
              :alt="movie.title" 
              class="w-32 md:w-48 rounded-lg shadow-xl"
              @error="useDefaultPoster"
            />
            <div>
              <h1 class="text-3xl md:text-4xl font-bold mb-2">{{ movie.title }}</h1>
              <p class="text-sm opacity-70">
                {{ releaseYear }} | 
                <span class="badge badge-accent">{{ formatRating }}</span>
              </p>
            </div>
          </div>
        </div>
      </div>
      
      <!-- Content Section -->
      <div class="container mx-auto p-4">
        <div class="flex flex-col md:flex-row gap-8">
          <!-- Main Content -->
          <div class="md:w-2/3">
            <div class="card bg-neutral-800 mb-8">
              <div class="card-body">
                <h2 class="card-title text-xl mb-2">Overview</h2>
                <p>{{ movie.overview || 'No overview available.' }}</p>
              </div>
            </div>
            
            <div class="card bg-neutral-800 mb-8">
              <div class="card-body">
                <h2 class="card-title text-xl mb-2">Download Options</h2>
                <p class="mb-4">Start downloading "{{ movie.title }}" now:</p>
                <button @click="downloadMovie" class="btn btn-primary">
                  <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                  </svg>
                  Find Download Options
                </button>
              </div>
            </div>
          </div>
          
          <!-- Sidebar -->
          <div class="md:w-1/3">
            <div class="card bg-neutral-800 mb-6">
              <div class="card-body">
                <h2 class="card-title text-xl mb-2">Movie Details</h2>
                <div class="overflow-x-auto">
                  <table class="table w-full">
                    <tbody>
                      <tr>
                        <td class="font-bold">Release Date</td>
                        <td>{{ formatDate }}</td>
                      </tr>
                      <tr>
                        <td class="font-bold">Rating</td>
                        <td>{{ movie.vote_average?.toFixed(1) || 'N/A' }}/10 ({{ movie.vote_count }} votes)</td>
                      </tr>
                      <tr>
                        <td class="font-bold">Genres</td>
                        <td>
                          <div class="flex flex-wrap gap-1">
                            <span 
                              v-for="genre in movie.genres" 
                              :key="genre.id" 
                              class="badge badge-outline"
                            >
                              {{ genre.name }}
                            </span>
                          </div>
                        </td>
                      </tr>
                      <tr v-if="movie.runtime">
                        <td class="font-bold">Runtime</td>
                        <td>{{ formatRuntime }}</td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import axios from 'axios'

// Define MovieDetail interface inline instead of importing it
interface MovieDetail {
  id: number
  title: string
  poster_path: string
  backdrop_path: string
  overview: string
  release_date: string
  vote_average: number
  vote_count: number
  genres: { id: number, name: string }[]
  runtime: number
}

const route = useRoute()
const router = useRouter()
const config = useRuntimeConfig()

const movieId = computed(() => route.params.id as string)
const movie = ref<MovieDetail>({} as MovieDetail)
const loading = ref(true)
const error = ref<string | null>(null)

const posterUrl = computed(() => {
  if (!movie.value.poster_path) return '/no-poster.jpg'
  return `${config.public.tmdbImageBaseUrl}/w500${movie.value.poster_path}`
})

const backdropUrl = computed(() => {
  if (!movie.value.backdrop_path) return ''
  return `${config.public.tmdbImageBaseUrl}/original${movie.value.backdrop_path}`
})

const formatRating = computed(() => {
  return movie.value.vote_average?.toFixed(1) || 'N/A'
})

const releaseYear = computed(() => {
  if (!movie.value.release_date) return 'Unknown year'
  return new Date(movie.value.release_date).getFullYear()
})

const formatDate = computed(() => {
  if (!movie.value.release_date) return 'Unknown date'
  return new Date(movie.value.release_date).toLocaleDateString()
})

const formatRuntime = computed(() => {
  if (!movie.value.runtime) return 'Unknown'
  const hours = Math.floor(movie.value.runtime / 60)
  const minutes = movie.value.runtime % 60
  return `${hours}h ${minutes}m`
})

function useDefaultPoster(event: Event) {
  const target = event.target as HTMLImageElement
  target.src = '/no-poster.jpg'
}

function downloadMovie() {
  router.push(`/download/${movie.value.id}`)
}

onMounted(async () => {
  try {
    loading.value = true
    error.value = null
    
    const response = await axios.get(`${config.public.tmdbApiBaseUrl}/movie/${movieId.value}`, {
      params: {
        api_key: config.public.tmdbApiKey
      }
    })
    
    movie.value = response.data
  } catch (err: any) {
    error.value = err.message || 'Failed to load movie'
  } finally {
    loading.value = false
  }
})
</script>