<!-- Generated by Copilot April 25, 2025 -->
<template>
  <div class="container mx-auto p-4">
    <h1 class="text-3xl font-bold mb-6">Movie Genres</h1>

    <!-- Genre Selection -->
    <div class="flex flex-wrap gap-2 mb-8">
      <button 
        v-for="genre in moviesStore.genres" 
        :key="genre.id"
        @click="selectGenre(genre.id)"
        class="btn" 
        :class="{'btn-primary': genre.id === currentGenreId, 'btn-outline': genre.id !== currentGenreId}"
      >
        {{ genre.name }}
      </button>
    </div>

    <div v-if="moviesStore.loading && !loadingMore" class="flex justify-center my-12">
      <span class="loading loading-spinner loading-lg text-red-600"></span>
    </div>

    <div v-else-if="moviesStore.error" class="alert alert-error shadow-lg mb-8">
      <div>
        <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current flex-shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" />
        </svg>
        <span>{{ moviesStore.error }}</span>
      </div>
    </div>

    <div v-else>
      <!-- Selected Genre Header -->
      <div v-if="selectedGenre" class="mb-6">
        <div class="flex justify-between items-center">
          <h2 class="text-2xl font-bold">{{ selectedGenre.name }} Movies</h2>
        </div>

        <!-- Movie Grid -->
        <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6 mt-6">
          <MovieCard v-for="movie in displayedMovies" :key="movie.id" :movie="movie" />
        </div>
        
        <!-- Empty State -->
        <div v-if="displayedMovies.length === 0 && !moviesStore.loading" class="text-center my-16">
          <p class="text-xl">No movies found in this genre. Try selecting another genre.</p>
        </div>
        
        <!-- Load More Button -->
        <div v-if="displayedMovies.length > 0 && hasMoreToLoad" class="flex justify-center mt-8 mb-4">
          <button 
            @click="loadMore" 
            class="btn btn-outline btn-accent"
            :class="{ 'btn-disabled': loadingMore }"
          >
            <span v-if="loadingMore" class="loading loading-spinner loading-sm mr-2"></span>
            Load More
          </button>
        </div>
      </div>
      
      <div v-else class="flex flex-col items-center justify-center my-16">
        <p class="text-xl mb-4">Please select a genre to see movies.</p>
        <svg xmlns="http://www.w3.org/2000/svg" class="h-16 w-16 opacity-50" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 4v16M17 4v16M3 8h4m10 0h4M3 12h18M3 16h4m10 0h4M4 20h16a1 1 0 001-1V5a1 1 0 00-1-1H4a1 1 0 00-1 1v14a1 1 0 001 1z" />
        </svg>
      </div>
    </div>
  </div>
  
  <!-- Scroll to top button -->
  <button 
    @click="scrollToTop" 
    class="btn btn-circle btn-primary fixed bottom-6 right-6 shadow-lg z-50"
    v-show="showScrollTop"
  >
    <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 10l7-7m0 0l7 7m-7-7v18" />
    </svg>
  </button>
</template>

<script setup lang="ts">
import { useMoviesStore, type Genre } from '~/stores/movies'
import { ref, computed, watch, onMounted, onUnmounted } from 'vue'

const moviesStore = useMoviesStore()
const route = useRoute()
const router = useRouter()

const currentPage = ref(1)
const currentGenreId = computed(() => moviesStore.currentGenreId)
const loadingMore = ref(false)
const showScrollTop = ref(false)
const allLoadedMovies = ref<any[]>([])

// Find the currently selected genre object
const selectedGenre = computed(() => {
  if (!currentGenreId.value) return null
  return moviesStore.genres.find(genre => genre.id === currentGenreId.value) || null
})

const displayedMovies = computed(() => {
  return allLoadedMovies.value
})

const hasMoreToLoad = computed(() => {
  return currentPage.value < moviesStore.totalGenrePages
})

function scrollToTop() {
  window.scrollTo({
    top: 0,
    behavior: 'smooth'
  })
}

function handleScroll() {
  showScrollTop.value = window.scrollY > 500
}

// Handle genre selection
async function selectGenre(genreId: number) {
  if (genreId === currentGenreId.value) return
  
  currentPage.value = 1
  allLoadedMovies.value = []
  
  await moviesStore.fetchMoviesByGenre(genreId, currentPage.value)
  allLoadedMovies.value = [...moviesStore.genreMovies]
  
  // Update URL to reflect selected genre
  router.push({ 
    path: '/genres', 
    query: { id: genreId.toString() } 
  })
}

// Load more movies
async function loadMore() {
  if (loadingMore.value || !hasMoreToLoad.value) return
  
  loadingMore.value = true
  currentPage.value++
  
  if (currentGenreId.value) {
    await moviesStore.fetchMoviesByGenre(currentGenreId.value, currentPage.value)
    // Append new movies to the existing ones
    allLoadedMovies.value = [...allLoadedMovies.value, ...moviesStore.genreMovies]
    
    // Update URL to reflect current page
    router.push({ 
      path: '/genres', 
      query: { 
        id: currentGenreId.value.toString(),
        page: currentPage.value.toString()
      } 
    })
  }
  
  loadingMore.value = false
}

// Initialize page
onMounted(async () => {
  // Load all genres if not already loaded
  if (moviesStore.genres.length === 0) {
    await moviesStore.fetchGenres()
  }
  
  // Check if we have a genre ID in the URL query parameters
  const genreId = route.query.id ? parseInt(route.query.id as string) : null
  const page = route.query.page ? parseInt(route.query.page as string) : 1
  
  if (genreId) {
    currentPage.value = page || 1
    await moviesStore.fetchMoviesByGenre(genreId, currentPage.value)
    allLoadedMovies.value = [...moviesStore.genreMovies]
    
    // If we started at a page > 1, load all previous pages
    if (currentPage.value > 1) {
      for (let i = 1; i < currentPage.value; i++) {
        await moviesStore.fetchMoviesByGenre(genreId, i)
        allLoadedMovies.value = [...allLoadedMovies.value, ...moviesStore.genreMovies]
      }
    }
  }
  
  // Add scroll event listener
  window.addEventListener('scroll', handleScroll)
})

// Watch for URL changes
watch(() => route.query, async (newQuery) => {
  const genreId = newQuery.id ? parseInt(newQuery.id as string) : null
  
  if (genreId && genreId !== currentGenreId.value) {
    currentPage.value = 1
    allLoadedMovies.value = []
    await moviesStore.fetchMoviesByGenre(genreId, currentPage.value)
    allLoadedMovies.value = [...moviesStore.genreMovies]
  }
}, { deep: true })

onUnmounted(() => {
  // Remove scroll event listener when component is destroyed
  window.removeEventListener('scroll', handleScroll)
})
</script>