<!-- Generated by Copilot 2025-04-25 -->
<template>
  <div>
    <div class="hero min-h-[500px] md:min-h-[600px] bg-neutral-900 relative overflow-hidden">
      <!-- Random movie backdrop image with improved positioning -->
      <div v-if="headerMovie" class="absolute inset-0 w-full h-full">
        <div class="absolute inset-0 bg-gradient-to-b from-neutral-900/70 via-neutral-900/50 to-neutral-900 z-10"></div>
        <img :src="`https://image.tmdb.org/t/p/original${headerMovie.backdrop_path}`" 
             alt="Movie backdrop" 
             class="w-full h-full object-cover object-top" />
      </div>
      
      <div class="hero-content text-center relative z-20 w-full px-4 md:px-8 py-16">
        <div class="max-w-2xl mx-auto">
          <h1 class="text-4xl md:text-5xl font-bold mb-6 text-white drop-shadow-md">CsetFlix</h1>

          <div class="flex flex-col sm:flex-row gap-3 justify-center mb-8">
            <NuxtLink v-if="headerMovie" :to="`/movie/${headerMovie.id}`" class="btn bg-red-600 hover:bg-red-700 border-red-700 text-white btn-lg">
              <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
              </svg>
              View Featured
            </NuxtLink>
            <button @click="fetchRandomClassicMovie" class="btn bg-neutral-800 hover:bg-neutral-700 border-neutral-700 text-white btn-lg">
              <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
              </svg>
              Random Movie
            </button>
          </div>
          
          <div v-if="headerMovie" class="featured-movie-info bg-neutral-800/80 backdrop-blur-sm p-4 rounded-lg border border-neutral-700 inline-block">
            <p class="font-medium text-xl mb-1">{{ headerMovie.title }}</p>
            <p class="text-sm text-gray-300">
              {{ headerMovie.release_date?.substring(0, 4) }} • 
              <span class="badge bg-red-600 border-red-700 text-white">{{ (headerMovie.vote_average || 0).toFixed(1) }}</span>
            </p>
          </div>
        </div>
      </div>
    </div>

    <div class="container mx-auto px-4 py-12 bg-neutral-900">
      <!-- Trending Movies -->
      <div class="mb-8 flex justify-between items-center">
        <h2 class="text-2xl md:text-3xl font-bold">
          <span class="text-red-600">Trending</span> This Week
        </h2>
      </div>
      
      <div v-if="moviesStore.loading && !loadingMore" class="flex justify-center my-12">
        <span class="loading loading-spinner loading-lg text-red-600"></span>
      </div>
      <div v-else-if="moviesStore.error" class="alert alert-error shadow-lg mb-8">
        <div>
          <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current flex-shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" />
          </svg>
          <span>{{ moviesStore.error }}</span>
        </div>
      </div>
      <div v-else class="grid grid-cols-2 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-4 md:gap-6">
        <MovieCard v-for="movie in displayedMovies" :key="movie.id" :movie="movie" />
      </div>
      
      <!-- Bottom Load More Button -->
      <div class="flex justify-center mt-12">
        <button 
          @click="loadMore" 
          class="btn border-red-700 bg-transparent hover:bg-red-800/30 text-red-500 hover:text-red-400 btn-lg px-8"
          :class="{ 'btn-disabled': moviesStore.loading }"
        >
          <span v-if="loadingMore" class="loading loading-spinner loading-sm mr-2"></span>
          Load More
        </button>
      </div>
    </div>

    <!-- Scroll to top button -->
    <button 
      @click="scrollToTop" 
      class="btn btn-circle bg-red-600 hover:bg-red-700 border-red-700 text-white btn-lg fixed bottom-6 right-6 shadow-xl z-50 animate-pulse-slow"
      v-show="showScrollTop"
    >
      <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 10l7-7m0 0l7 7m-7-7v18" />
      </svg>
    </button>
  </div>
</template>

<script setup lang="ts">
import { useMoviesStore } from '~/stores/movies'
import axios from 'axios'
import { ref, computed, onMounted, onUnmounted } from 'vue'

const moviesStore = useMoviesStore()
const headerMovie = ref(null)
const currentPage = ref(1)
const moviesPerPage = 16
const loadingMore = ref(false)
const showScrollTop = ref(false)

const displayedMovies = computed(() => {
  return moviesStore.trendingMovies.slice(0, currentPage.value * moviesPerPage)
})

function scrollToTop() {
  window.scrollTo({
    top: 0,
    behavior: 'smooth'
  })
}

function handleScroll() {
  showScrollTop.value = window.scrollY > 500
}

async function loadMore() {
  loadingMore.value = true
  currentPage.value++
  
  // Check if we need to fetch more movies from the API
  if (displayedMovies.value.length >= moviesStore.trendingMovies.length) {
    await moviesStore.fetchTrendingPage(Math.ceil(displayedMovies.value.length / 20) + 1)
  }
  
  loadingMore.value = false
}

// Get a random classic movie for the header
async function fetchRandomClassicMovie() {
  try {
    // Get a random page between 1-10 of classic movies from TMDB
    const randomPage = Math.floor(Math.random() * 10) + 1
    
    // Use a year range for classic movies (e.g., before 1990)
    const response = await axios.get('https://api.themoviedb.org/3/discover/movie', {
      params: {
        api_key: '262d5ff6a75ab6f20cf8594e41b2ac86',
        language: 'en-US',
        sort_by: 'popularity.desc',
        include_adult: false,
        page: randomPage,
        'primary_release_date.lte': '1990-12-31',
        'vote_count.gte': 100,
        with_backdrop_path: true
      }
    })
    
    if (response.data.results && response.data.results.length > 0) {
      // Select a random movie from the results
      const randomIndex = Math.floor(Math.random() * response.data.results.length)
      headerMovie.value = response.data.results[randomIndex]
    }
  } catch (error) {
    console.error('Error fetching random classic movie:', error)
  }
}

onMounted(async () => {
  // Fetch the header image
  await fetchRandomClassicMovie()
  
  // Fetch movies if not already loaded
  if (moviesStore.trendingMovies.length === 0) {
    await moviesStore.fetchTrending()
  }

  // Add scroll event listener
  window.addEventListener('scroll', handleScroll)
})

onUnmounted(() => {
  // Remove scroll event listener when component is destroyed
  window.removeEventListener('scroll', handleScroll)
})
</script>

<style scoped>
.animate-pulse-slow {
  animation: pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite;
}

@keyframes pulse {
  0%, 100% {
    opacity: 1;
  }
  50% {
    opacity: 0.7;
  }
}
</style>