<!-- Generated by Copilot 2025-04-23 14:22 -->
<template>
  <div>
    <div class="hero bg-neutral-800 py-12">
      <div class="hero-content text-center">
        <div class="max-w-xl">
          <h1 class="text-4xl font-bold">CsetFlix</h1>
          <p class="py-6">Your personal media center for browsing, discovering, and downloading movies. Integrated with qBittorrent and Jellyfin for a seamless media experience.</p>
          <NuxtLink to="/movies" class="btn btn-primary">Browse Movies</NuxtLink>
        </div>
      </div>
    </div>

    <div class="container mx-auto p-4">
      <!-- Trending Movies -->
      <h2 class="text-2xl font-bold my-6">Trending This Week</h2>
      <div v-if="moviesStore.loading" class="flex justify-center my-8">
        <span class="loading loading-spinner loading-lg text-red-600"></span>
      </div>
      <div v-else-if="moviesStore.error" class="alert alert-error shadow-lg mb-4">
        <div>
          <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current flex-shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" />
          </svg>
          <span>{{ moviesStore.error }}</span>
        </div>
      </div>
      <div v-else class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
        <MovieCard v-for="movie in moviesStore.trendingMovies.slice(0, 8)" :key="movie.id" :movie="movie" />
      </div>
      
      <!-- Popular Movies -->
      <h2 class="text-2xl font-bold my-6">Popular Movies</h2>
      <div v-if="moviesStore.loading" class="flex justify-center my-8">
        <span class="loading loading-spinner loading-lg text-red-600"></span>
      </div>
      <div v-else class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
        <MovieCard v-for="movie in moviesStore.popularMovies.slice(0, 8)" :key="movie.id" :movie="movie" />
      </div>

      <div class="flex justify-center mt-8">
        <NuxtLink to="/movies" class="btn btn-outline">View All Movies</NuxtLink>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { useMoviesStore } from '~/stores/movies'

const moviesStore = useMoviesStore()

onMounted(async () => {
  if (moviesStore.trendingMovies.length === 0) {
    await moviesStore.fetchTrending()
  }
  
  if (moviesStore.popularMovies.length === 0) {
    await moviesStore.fetchPopular()
  }
})
</script>