<!-- Generated by Copilot 2025-04-23 14:25 -->
<template>
  <div class="container mx-auto p-4">
    <h1 class="text-3xl font-bold mb-6">Movies</h1>
    
    <div class="flex justify-between mb-6">
      <div class="tabs tabs-boxed">
        <button 
          class="tab" 
          :class="{ 'tab-active': activeTab === 'trending' }"
          @click="setActiveTab('trending')"
        >
          Trending
        </button>
        <button 
          class="tab" 
          :class="{ 'tab-active': activeTab === 'popular' }"
          @click="setActiveTab('popular')"
        >
          Popular
        </button>
      </div>
    </div>
    
    <div v-if="moviesStore.loading" class="flex justify-center my-8">
      <span class="loading loading-spinner loading-lg text-red-600"></span>
    </div>
    
    <div v-else-if="moviesStore.error" class="alert alert-error shadow-lg mb-4">
      <div>
        <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current flex-shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" />
        </svg>
        <span>{{ moviesStore.error }}</span>
      </div>
    </div>
    
    <div v-else class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-6">
      <MovieCard 
        v-for="movie in displayedMovies" 
        :key="movie.id" 
        :movie="movie" 
      />
    </div>
    
    <div v-if="!moviesStore.loading && displayedMovies.length === 0" class="text-center my-8">
      <p>No movies found.</p>
    </div>
  </div>
</template>

<script setup lang="ts">
import { useMoviesStore } from '~/stores/movies'

const moviesStore = useMoviesStore()
const activeTab = ref('trending')

const displayedMovies = computed(() => {
  if (activeTab.value === 'trending') {
    return moviesStore.trendingMovies
  } else {
    return moviesStore.popularMovies
  }
})

async function setActiveTab(tab: string) {
  activeTab.value = tab
  
  if (tab === 'trending' && moviesStore.trendingMovies.length === 0) {
    await moviesStore.fetchTrending()
  } else if (tab === 'popular' && moviesStore.popularMovies.length === 0) {
    await moviesStore.fetchPopular()
  }
}

onMounted(async () => {
  if (moviesStore.trendingMovies.length === 0) {
    await moviesStore.fetchTrending()
  }
})
</script>