<!-- Generated by Copilot 2025-04-23 14:30 -->
<template>
  <div class="container mx-auto p-4">
    <h1 class="text-3xl font-bold mb-6">Search Movies</h1>
    
    <div class="form-control mb-8">
      <div class="input-group w-full">
        <input 
          v-model="searchQuery" 
          type="text" 
          placeholder="Enter movie title..." 
          class="input input-bordered w-full bg-neutral-800" 
          @keyup.enter="searchMovies"
        />
        <button class="btn btn-primary" @click="searchMovies">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
          </svg>
        </button>
      </div>
    </div>
    
    <div v-if="moviesStore.loading" class="flex justify-center my-8">
      <span class="loading loading-spinner loading-lg text-red-600"></span>
    </div>
    
    <div v-else-if="moviesStore.error" class="alert alert-error shadow-lg mb-4">
      <div>
        <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current flex-shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" />
        </svg>
        <span>{{ moviesStore.error }}</span>
      </div>
    </div>
    
    <div v-else-if="searchWasPerformed && moviesStore.searchResults.length === 0" class="text-center my-12">
      <p class="text-xl">No movies found matching "{{ lastQuery }}"</p>
      <p class="mt-2 text-neutral-400">Try searching with different keywords</p>
    </div>
    
    <div v-else-if="searchWasPerformed" class="mt-4">
      <p class="mb-4">Search results for "{{ lastQuery }}":</p>
      <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-6">
        <MovieCard 
          v-for="movie in moviesStore.searchResults" 
          :key="movie.id" 
          :movie="movie" 
        />
      </div>
    </div>
    
    <div v-else class="text-center my-12">
      <p class="text-xl">Enter a movie title to search</p>
    </div>
  </div>
</template>

<script setup lang="ts">
import { useMoviesStore } from '~/stores/movies'

const route = useRoute()
const moviesStore = useMoviesStore()
const searchQuery = ref('')
const searchWasPerformed = ref(false)
const lastQuery = ref('')

async function searchMovies() {
  if (!searchQuery.value.trim()) return
  
  lastQuery.value = searchQuery.value
  await moviesStore.searchMovies(searchQuery.value)
  searchWasPerformed.value = true
}

onMounted(async () => {
  const query = route.query.q as string
  if (query) {
    searchQuery.value = query
    await searchMovies()
  }
})
</script>